/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin;

import anhht.gui.admin.insert.AccInsertFrame;
import anht.daos.CustomerDAO;
import anht.dtos.CustomerDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuana
 */
public class AccountPanel extends javax.swing.JPanel {

    private DefaultTableModel tblModelAccount = null;

    /**
     * Creates new form AccountPanel
     */
    public AccountPanel() {
        initComponents();
        tblModelAccount = (DefaultTableModel) tblViewAccount.getModel();
    }

    private void showAccount(List<CustomerDTO> list) {
        tblModelAccount.setRowCount(0);
        for (CustomerDTO accountDTO : list) {
            tblModelAccount.addRow(accountDTO.toVector());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSex = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewAccount = new javax.swing.JTable();
        pnlUserInfo = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblSex = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        msgPass = new javax.swing.JLabel();
        msgName = new javax.swing.JLabel();
        msgAge = new javax.swing.JLabel();
        msgPhone = new javax.swing.JLabel();
        msgPass2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblCarList = new javax.swing.JLabel();
        lblCarInfo = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViewAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblViewAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AccID", "Password", "Name", "Sex", "Age", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewAccount.setRowHeight(24);
        tblViewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewAccount);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 670, 520));

        pnlUserInfo.setBackground(new java.awt.Color(204, 255, 153));
        pnlUserInfo.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.setPreferredSize(new java.awt.Dimension(51, 20));
        pnlUserInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblUsername.setText("Username:");
        pnlUserInfo.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 31, -1, 30));

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 255, 51));
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 30, 390, -1));

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPass.setText("Password:");
        pnlUserInfo.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 106, 28));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 255, 51));
        txtPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 107, 390, -1));

        lblSex.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSex.setText("Sex:");
        pnlUserInfo.add(lblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 270, -1, 37));

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtAge.setForeground(new java.awt.Color(51, 255, 51));
        txtAge.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 363, 100, -1));

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblAge.setText("Age:");
        pnlUserInfo.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 365, -1, 28));

        rdMale.setBackground(new java.awt.Color(204, 255, 153));
        groupSex.add(rdMale);
        rdMale.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdMale.setSelected(true);
        rdMale.setText("Male");
        pnlUserInfo.add(rdMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 271, -1, -1));

        rdFemale.setBackground(new java.awt.Color(204, 255, 153));
        groupSex.add(rdFemale);
        rdFemale.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdFemale.setText("Female");
        pnlUserInfo.add(rdFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPhone.setText("Phone Number:");
        pnlUserInfo.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 451, -1, 28));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(51, 255, 51));
        txtPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 449, 210, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblName.setText("Fullname:");
        pnlUserInfo.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 186, -1, 28));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 255, 51));
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 184, 390, -1));

        msgPass.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 149, 386, 17));

        msgName.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 226, 183, 17));

        msgAge.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 405, 183, 17));

        msgPhone.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 491, 183, 14));

        msgPass2.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 167, 386, 17));

        add(pnlUserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 660, 530));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 640, 110, 40));

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 110, 40));

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, -1, 40));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 190, 40));

        lblID.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblID.setText("AccID:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, 40));

        lblCarList.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarList.setText("Account List");
        add(lblCarList, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        lblCarInfo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarInfo.setText("Account Info");
        add(lblCarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnDelete.setText("Remove");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, -1, 40));

        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 630, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String accID = txtUsername.getText();
        String pass = new String(txtPass.getPassword());
        String fullname = txtName.getText();
        String phone = txtPhone.getText();
        boolean sex = rdMale.isSelected();
        int age = 0;
        try {
            age = Integer.parseInt(txtAge.getText());
        } catch (NumberFormatException e) {
        }
        CustomerDAO accDAO = new CustomerDAO();
        if (validate(accID, pass, fullname, phone, age)) {
            if (accDAO.update(new CustomerDTO(accID, pass, fullname, phone, sex, age))) {
                JOptionPane.showMessageDialog(null, "Update success");
                btnDelete.setEnabled(false);
                btnSearch.doClick();
                btnReset.doClick();
                txtUsername.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Update failed");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtPass.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtAge.setText("");
        rdMale.setSelected(true);
        msgPass.setText("");
        msgPass2.setText("");
        msgName.setText("");
        msgPhone.setText("");
        msgAge.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        CustomerDAO accDAO = new CustomerDAO();
        List<CustomerDTO> result = null;
        if (txtSearch.getText().equals("")) {
            result = accDAO.findAllUsers();
        } else {
            CustomerDTO accDTO = accDAO.findByPrimaryKey(txtSearch.getText());
            if (accDTO != null) {
                result = new ArrayList<>();
                result.add(accDTO);
            }
        }
        if (result != null && !result.isEmpty()) {
            showAccount(result);
        } else {
            JOptionPane.showMessageDialog(null, "Not Found!");
            tblModelAccount.setRowCount(0);
        }
        btnDelete.setEnabled(false);
        btnReset.doClick();
        txtUsername.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblViewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewAccountMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblViewAccount.getSelectedRow();
            String accID = (String) tblModelAccount.getValueAt(row, 0);
            loadAccount(accID);
            btnDelete.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select account");
        }

    }//GEN-LAST:event_tblViewAccountMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblViewAccount.getSelectedRow();
            String accID = (String) tblModelAccount.getValueAt(row, 0);
            CustomerDAO accDAO = new CustomerDAO();
            if (accDAO.delete(accID)) {
                JOptionPane.showMessageDialog(null, "Delete success");
                btnDelete.setEnabled(false);
                btnReset.doClick();
                txtUsername.setText("");
                if (txtSearch.getText().equals("")) {
                    btnSearch.doClick();
                } else {
                    tblModelAccount.setRowCount(0);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Delete failed. This account can contain some transactions.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select account");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        new AccInsertFrame(btnSearch, btnDelete, btnReset, txtSearch, txtUsername).setVisible(true);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void loadAccount(String accID) {
        CustomerDAO accDAO = new CustomerDAO();
        CustomerDTO accDTO = accDAO.findByPrimaryKey(accID);
        if (accDTO != null) {
            txtUsername.setText(accDTO.getId());
            txtPass.setText(accDTO.getPassword());
            txtName.setText(accDTO.getName());
            if (accDTO.isSex()) {
                rdMale.setSelected(true);
            } else {
                rdFemale.setSelected(true);
            }
            txtAge.setText(Integer.toString(accDTO.getAge()));
            txtPhone.setText(accDTO.getPhone());
        } else {
            JOptionPane.showMessageDialog(null, "Cannot load user information", "System warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private boolean validate(String username, String pass, String fullname, String phone, int age) {
        boolean check = true;
        String passPattern = "(?=.*\\d)(?=.*[a-zA-Z])[\\w]{8,}";
        String phonePattern = "\\d{10}";
        if (username.equals("")) {
            check = false;
            JOptionPane.showMessageDialog(null, "Please choose account");
        } else {
            if (!pass.matches(passPattern)) {
                msgPass.setText("Password must be 8 or more alphanumberic characters");
                msgPass2.setText("including at least 1 letter and 1 numberic letter.");
                check = false;
            } else {
                msgPass.setText("");
                msgPass2.setText("");
            }
            if (fullname.equals("")) {
                msgName.setText("Full name is not empty.");
                check = false;
            } else {
                msgName.setText("");
            }
            if (!phone.matches(phonePattern)) {
                msgPhone.setText("Phone is the sequence of 10 digits.");
                check = false;
            } else {
                msgPhone.setText("");
            }

            if (age < 1) {
                msgAge.setText("Age is a positive number");
                check = false;
            } else {
                msgAge.setText("");
            }
        }
        return check;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup groupSex;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCarInfo;
    private javax.swing.JLabel lblCarList;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel msgAge;
    private javax.swing.JLabel msgName;
    private javax.swing.JLabel msgPass;
    private javax.swing.JLabel msgPass2;
    private javax.swing.JLabel msgPhone;
    private javax.swing.JPanel pnlUserInfo;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTable tblViewAccount;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
