/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin;

import anhht.gui.admin.insert.CarCatInsertFrame;
import anhht.daos.CarCategoryDAO;
import anhht.dtos.CarCategoryDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuana
 */
public class CarCategoryPanel extends javax.swing.JPanel {

    private DefaultTableModel tblModelCarCategory = null;

    /**
     * Creates new form CarCategoryPanel
     */
    public CarCategoryPanel() {
        initComponents();
        tblModelCarCategory = (DefaultTableModel) tblViewCarCategory.getModel();
        spSeats.setEnabled(false);
        ((JSpinner.DefaultEditor) spSearch.getEditor()).getTextField().setEditable(false);
    }

    private void showCarCategory(List<CarCategoryDTO> list) {
        tblModelCarCategory.setRowCount(0);
        for (CarCategoryDTO carCategoryDTO : list) {
            tblModelCarCategory.addRow(carCategoryDTO.toVector());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCarCategory = new javax.swing.JTable();
        lblCarList = new javax.swing.JLabel();
        lblCarInfo = new javax.swing.JLabel();
        pnlCarCatInfo = new javax.swing.JPanel();
        lblSeats = new javax.swing.JLabel();
        lblSurchargeHr = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        spSeats = new javax.swing.JSpinner();
        txtSurcharge = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        lblVND = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        msgSurcharge = new javax.swing.JLabel();
        msgDiscount = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        spSearch = new javax.swing.JSpinner();
        btnshowAll = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViewCarCategory.setAutoCreateRowSorter(true);
        tblViewCarCategory.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tblViewCarCategory.setForeground(new java.awt.Color(51, 51, 255));
        tblViewCarCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number Of Seats", "SurchargeHr (VND)", "Discount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewCarCategory.setRowHeight(24);
        tblViewCarCategory.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblViewCarCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewCarCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewCarCategory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 590, 410));

        lblCarList.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarList.setForeground(new java.awt.Color(255, 0, 0));
        lblCarList.setText("Car Category List");
        add(lblCarList, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        lblCarInfo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarInfo.setForeground(new java.awt.Color(255, 0, 0));
        lblCarInfo.setText("Car Category Info");
        add(lblCarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 80, -1, -1));

        pnlCarCatInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCarCatInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        pnlCarCatInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSeats.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSeats.setForeground(new java.awt.Color(51, 51, 255));
        lblSeats.setText("Seats:");
        pnlCarCatInfo.add(lblSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 27, -1, 40));

        lblSurchargeHr.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSurchargeHr.setForeground(new java.awt.Color(51, 51, 255));
        lblSurchargeHr.setText("SurchargeHr:");
        pnlCarCatInfo.add(lblSurchargeHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        lblDiscount.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(51, 51, 255));
        lblDiscount.setText("Discount:");
        pnlCarCatInfo.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 30));

        spSeats.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spSeats.setModel(new javax.swing.SpinnerNumberModel(2, 2, 100, 1));
        spSeats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCarCatInfo.add(spSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        txtSurcharge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSurcharge.setForeground(new java.awt.Color(51, 51, 255));
        pnlCarCatInfo.add(txtSurcharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 180, -1));

        txtDiscount.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(51, 51, 255));
        pnlCarCatInfo.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 180, -1));

        lblVND.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblVND.setForeground(new java.awt.Color(51, 51, 255));
        lblVND.setText("VND");
        pnlCarCatInfo.add(lblVND, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 117, -1, 40));

        lblPercent.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPercent.setForeground(new java.awt.Color(51, 51, 255));
        lblPercent.setText("%");
        pnlCarCatInfo.add(lblPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, 30));

        msgSurcharge.setForeground(new java.awt.Color(255, 0, 0));
        pnlCarCatInfo.add(msgSurcharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 20));

        msgDiscount.setForeground(new java.awt.Color(255, 0, 0));
        pnlCarCatInfo.add(msgDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 20));

        add(pnlCarCatInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 490, 300));

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 0, 0));
        lblSearch.setText("Seats:");
        add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, 50));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 0, 0));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/searching-2339723_1920.png"))); // NOI18N
        btnSearch.setToolTipText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 50, 50));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/cancel.png"))); // NOI18N
        btnDelete.setToolTipText("Remove");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 50, 50));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 0, 0));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/add-1-icon.png"))); // NOI18N
        btnInsert.setToolTipText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 50, 50));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 0));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/5c8dd48504f17.png"))); // NOI18N
        btnReset.setToolTipText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 480, 60, 50));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 0, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/24b70afe9c.png"))); // NOI18N
        btnUpdate.setToolTipText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 480, 60, 50));

        spSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spSearch.setModel(new javax.swing.SpinnerNumberModel(2, 2, 100, 1));
        spSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(spSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, -1, 50));

        btnshowAll.setBackground(new java.awt.Color(255, 255, 255));
        btnshowAll.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnshowAll.setForeground(new java.awt.Color(255, 0, 0));
        btnshowAll.setText("Show All");
        btnshowAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnshowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowAllActionPerformed(evt);
            }
        });
        add(btnshowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, 40));

        lblBackground.setBackground(new java.awt.Color(255, 255, 255));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 2660, 1220));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int seats = (Integer) spSeats.getValue();
        int surchargeHr = 0;
        float discount = 0;
        try {
            surchargeHr = Integer.parseInt(txtSurcharge.getText());
        } catch (NumberFormatException e) {
        }
        try {
            int temp = Integer.parseInt(txtDiscount.getText());
            discount = (float) Math.round(temp) / 100;
        } catch (NumberFormatException e) {
        }
        CarCategoryDAO carCatDAO = new CarCategoryDAO();
        if (validate(seats, surchargeHr, discount)) {
            int dialogBtn = JOptionPane.showConfirmDialog(null, "Are you sure want to save changes?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogBtn == JOptionPane.YES_OPTION) {
                if (carCatDAO.update(new CarCategoryDTO(seats, surchargeHr, discount))) {
                    JOptionPane.showMessageDialog(null, "Update success");
                    int search = (Integer) spSearch.getValue();
                    if (search == seats) {
                        btnSearch.doClick();
                    } else {
                        btnshowAll.doClick();
                    }
                    spSeats.setValue(2);
                    btnDelete.setEnabled(false);
                    btnReset.doClick();
                } else {
                    JOptionPane.showMessageDialog(null, "Update failed");
                }
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtDiscount.setText("");
        txtSurcharge.setText("");
        msgDiscount.setText("");
        msgSurcharge.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        CarCategoryDAO carCatDAO = new CarCategoryDAO();
        List<CarCategoryDTO> result = null;
        int seats = (Integer) spSearch.getValue();
        CarCategoryDTO carCatDTO = carCatDAO.findByPrimaryKey(seats);
        if (carCatDTO != null) {
            result = new ArrayList<>();
            result.add(carCatDTO);
        }
        if (result != null) {
            showCarCategory(result);
        } else {
            JOptionPane.showMessageDialog(null, "Not Found!");
            tblModelCarCategory.setRowCount(0);
        }
        btnDelete.setEnabled(false);
        btnReset.doClick();
        spSeats.setValue(2);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnshowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowAllActionPerformed
        // TODO add your handling code here:
        CarCategoryDAO carCatDAO = new CarCategoryDAO();
        List<CarCategoryDTO> result = carCatDAO.findAll();
        if (result != null) {
            showCarCategory(result);
        } else {
            JOptionPane.showMessageDialog(null, "Not Found!");
            tblModelCarCategory.setRowCount(0);
        }
        btnDelete.setEnabled(false);
        btnReset.doClick();
        spSeats.setValue(2);
    }//GEN-LAST:event_btnshowAllActionPerformed

    private void tblViewCarCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewCarCategoryMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblViewCarCategory.getSelectedRow();
            int seats = (Integer) tblModelCarCategory.getValueAt(row, 0);
            loadCarCategoryInfo(seats);
            btnDelete.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select category");
        }
    }//GEN-LAST:event_tblViewCarCategoryMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblViewCarCategory.getSelectedRow();
            int seats = (Integer) tblModelCarCategory.getValueAt(row, 0);
            CarCategoryDAO ccDAO = new CarCategoryDAO();
            int dialogBtn = JOptionPane.showConfirmDialog(null, "Are you sure want to remove?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogBtn == JOptionPane.YES_OPTION) {
                if (ccDAO.delete(seats)) {
                    JOptionPane.showMessageDialog(null, "Delete success");
                    btnDelete.setEnabled(false);
                    btnReset.doClick();
                    spSeats.setValue(2);
                    int search = (Integer) spSearch.getValue();
                    if (search != seats) {
                        btnshowAll.doClick();
                    } else {
                        tblModelCarCategory.setRowCount(0);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Delete failed. There "
                            + "may be cars or travel price in this category.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select category");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        new CarCatInsertFrame(btnshowAll, btnDelete, btnReset, spSearch, spSeats).setVisible(true);
    }//GEN-LAST:event_btnInsertActionPerformed

    private boolean validate(int seats, int surchargeHr, float discount) {
        boolean check = true;
        CarCategoryDAO ccDAO = new CarCategoryDAO();
        CarCategoryDTO ccDTO = ccDAO.findByPrimaryKey(seats);
        if (ccDTO == null) {
            check = false;
            JOptionPane.showMessageDialog(null, "Please choose category");
        } else {
            if (surchargeHr < 1) {
                msgSurcharge.setText("Sucharge is number format.");
                check = false;
            } else {
                msgSurcharge.setText("");
            }
            if (discount < 1.0f && discount > 0) {
                msgDiscount.setText("");
            } else {
                msgDiscount.setText("Discount is invalid.");
                check = false;
            }
        }
        return check;
    }

    private void loadCarCategoryInfo(int seats) {
        CarCategoryDAO ccDAO = new CarCategoryDAO();
        CarCategoryDTO ccDTO = ccDAO.findByPrimaryKey(seats);
        if (ccDTO != null) {
            spSeats.setValue(ccDTO.getNumberOfSeats());
            txtSurcharge.setText(Integer.toString(ccDTO.getSurchargeHr()));
            txtDiscount.setText(Integer.toString(Math.round(ccDTO.getDiscount() * 100)));
        } else {
            JOptionPane.showMessageDialog(null, "Cannot load car category information", "System warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnshowAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblCarInfo;
    private javax.swing.JLabel lblCarList;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSurchargeHr;
    private javax.swing.JLabel lblVND;
    private javax.swing.JLabel msgDiscount;
    private javax.swing.JLabel msgSurcharge;
    private javax.swing.JPanel pnlCarCatInfo;
    private javax.swing.JSpinner spSearch;
    private javax.swing.JSpinner spSeats;
    private javax.swing.JTable tblViewCarCategory;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtSurcharge;
    // End of variables declaration//GEN-END:variables

}
