/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin;

import anhht.daos.CarCategoryDAO;
import anhht.daos.CarDAO;
import anhht.dtos.CarCategoryDTO;
import anhht.dtos.CarDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuana
 */
public class CarPanel extends javax.swing.JPanel {

    private DefaultTableModel tblModelCar = null;

    /**
     * Creates new form CarPanel
     */
    public CarPanel() {
        initComponents();
        tblModelCar = (DefaultTableModel) tblViewCar.getModel();
        loadCbCarCategory();
    }

    private void showCar(List<CarDTO> list) {
        tblModelCar.setRowCount(0);
        for (CarDTO carDTO : list) {
            tblModelCar.addRow(carDTO.toVector());
        }
    }

    private void loadCbCarCategory() {
        CarCategoryDAO carCateDAO = new CarCategoryDAO();
        List<CarCategoryDTO> result = carCateDAO.findAll();
        for (CarCategoryDTO carCategoryDTO : result) {
            cbSeats.addItem(Integer.toString(carCategoryDTO.getNumberOfSeats()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupAvailable = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewCar = new javax.swing.JTable();
        pnlCarInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cbSeats = new javax.swing.JComboBox<>();
        rdTrue = new javax.swing.JRadioButton();
        rdFalse = new javax.swing.JRadioButton();
        msgName = new javax.swing.JLabel();
        msgSerial = new javax.swing.JLabel();
        lblCarInfo = new javax.swing.JLabel();
        lblCarList = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblViewCar.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tblViewCar.setForeground(new java.awt.Color(51, 51, 255));
        tblViewCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Serial", "Name", "Seats", "Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewCar.setRowHeight(24);
        tblViewCar.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblViewCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewCarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewCar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 740, 500));

        pnlCarInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCarInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        pnlCarInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Serial:");
        pnlCarInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Name:");
        pnlCarInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Seats:");
        pnlCarInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Available:");
        pnlCarInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txtSerial.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSerial.setForeground(new java.awt.Color(51, 51, 255));
        pnlCarInfo.add(txtSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 280, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 51, 255));
        pnlCarInfo.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 280, -1));

        cbSeats.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cbSeats.setForeground(new java.awt.Color(51, 51, 255));
        cbSeats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCarInfo.add(cbSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        groupAvailable.add(rdTrue);
        rdTrue.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdTrue.setForeground(new java.awt.Color(51, 51, 255));
        rdTrue.setSelected(true);
        rdTrue.setText("True");
        rdTrue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCarInfo.add(rdTrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        groupAvailable.add(rdFalse);
        rdFalse.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdFalse.setForeground(new java.awt.Color(51, 51, 255));
        rdFalse.setText("False");
        rdFalse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCarInfo.add(rdFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, 30));

        msgName.setForeground(new java.awt.Color(255, 51, 51));
        pnlCarInfo.add(msgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 280, 20));

        msgSerial.setForeground(new java.awt.Color(255, 51, 51));
        pnlCarInfo.add(msgSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 280, 20));

        add(pnlCarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 490, 500));

        lblCarInfo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarInfo.setForeground(new java.awt.Color(255, 0, 0));
        lblCarInfo.setText("Car Info");
        add(lblCarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, -1, -1));

        lblCarList.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarList.setForeground(new java.awt.Color(255, 0, 0));
        lblCarList.setText("Car List");
        add(lblCarList, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 0, 0));
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, 230, 50));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/searching-2339723_1920.png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 50, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Serial:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, -1, 50));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 0));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/5c8dd48504f17.png"))); // NOI18N
        btnReset.setToolTipText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 630, 50, 50));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/cancel.png"))); // NOI18N
        btnDelete.setToolTipText("Remove");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 630, 50, 50));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 0, 0));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/add-1-icon.png"))); // NOI18N
        btnInsert.setToolTipText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 630, 50, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 2660, 1220));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblViewCar.getSelectedRow();
            String carSerial = (String) tblModelCar.getValueAt(row, 0);
            CarDAO carDAO = new CarDAO();
            int dialogBtn = JOptionPane.showConfirmDialog(null, "Are you sure want to remove?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogBtn == JOptionPane.YES_OPTION) {
                if (carDAO.delete(carSerial)) {
                    JOptionPane.showMessageDialog(null, "Delete success");
                    btnDelete.setEnabled(false);
                    if (txtSearch.getText().equals("")) {
                        btnSearch.doClick();
                    } else {
                        tblModelCar.setRowCount(0);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Delete failed. This car can be in some transacions.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select car");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        String carSerial = txtSerial.getText();
        String name = txtName.getText();
        boolean isAvailable = rdTrue.isSelected();
        int seats = Integer.parseInt((String) cbSeats.getSelectedItem());
        CarDAO carDAO = new CarDAO();
        if (validate(carSerial, name)) {
            if (carDAO.insert(new CarDTO(carSerial, name, seats, isAvailable))) {
                JOptionPane.showMessageDialog(null, "Insert success");
                btnDelete.setEnabled(false);
                txtSearch.setText("");
                btnSearch.doClick();
                btnReset.doClick();
            } else {
                JOptionPane.showMessageDialog(null, "Insert failed");
            }

        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtSerial.setText("");
        txtName.setText("");
        cbSeats.setSelectedIndex(0);
        rdTrue.setSelected(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        CarDAO carDAO = new CarDAO();
        List<CarDTO> result = null;
        if (txtSearch.getText().equals("")) {
            result = carDAO.findAll();
        } else {
            CarDTO carDTO = carDAO.findByPrimaryKey(txtSearch.getText());
            if (carDTO != null) {
                result = new ArrayList<>();
                result.add(carDTO);
            }
        }
        if (result != null && !result.isEmpty()) {
            showCar(result);
        } else {
            JOptionPane.showMessageDialog(null, "Not Found!");
            tblModelCar.setRowCount(0);
        }
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblViewCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewCarMouseClicked
        // TODO add your handling code here:
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblViewCarMouseClicked

    private boolean validate(String carSerial, String name) {
        boolean check = true;
        CarDAO carDAO = new CarDAO();
        String serialPattern = "\\d{2}[A-Z]\\d{5}";
        if (!carSerial.matches(serialPattern)) {
            msgSerial.setText("Serial format xxDxxxxx. Ex: 59G22132");
            check = false;
        } else if (carDAO.findExisting(carSerial)) {
            msgSerial.setText("Serial existed.");
            check = false;
        } else {
            msgSerial.setText("");
        }
        if (name.equals("")) {
            msgName.setText("Name is not empty.");
            check = false;
        } else {
            msgName.setText("");
        }
        return check;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbSeats;
    private javax.swing.ButtonGroup groupAvailable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarInfo;
    private javax.swing.JLabel lblCarList;
    private javax.swing.JLabel msgName;
    private javax.swing.JLabel msgSerial;
    private javax.swing.JPanel pnlCarInfo;
    private javax.swing.JRadioButton rdFalse;
    private javax.swing.JRadioButton rdTrue;
    private javax.swing.JTable tblViewCar;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSerial;
    // End of variables declaration//GEN-END:variables
}
