/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin;

import anhht.gui.admin.insert.EmpInsertFrame;
import anhht.daos.EmpDAO;
import anhht.dtos.EmployeeDTO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuana
 */
public class EmployeePanel extends javax.swing.JPanel {

    private DefaultTableModel tblModelEmployee = null;

    /**
     * Creates new form EmployeePanel
     */
    public EmployeePanel() {
        initComponents();
        tblModelEmployee = (DefaultTableModel) tblViewEmployee.getModel();
        ((JSpinner.DefaultEditor) spCertificate.getEditor()).getTextField().setEditable(false);
    }

    private void showEmployee(List<EmployeeDTO> list) {
        tblModelEmployee.setRowCount(0);
        for (EmployeeDTO employeeDTO : list) {
            tblModelEmployee.addRow(employeeDTO.toVector());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupAvailable = new javax.swing.ButtonGroup();
        groupSex = new javax.swing.ButtonGroup();
        lblCarList = new javax.swing.JLabel();
        lblCarInfo = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewEmployee = new javax.swing.JTable();
        pnlEmpInfo = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        msgName = new javax.swing.JLabel();
        msgAge = new javax.swing.JLabel();
        msgPhone = new javax.swing.JLabel();
        rdTrue = new javax.swing.JRadioButton();
        rdFalse = new javax.swing.JRadioButton();
        lblCertificate = new javax.swing.JLabel();
        spCertificate = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarList.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarList.setForeground(new java.awt.Color(255, 0, 51));
        lblCarList.setText("Employee List");
        add(lblCarList, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        lblCarInfo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarInfo.setForeground(new java.awt.Color(255, 0, 51));
        lblCarInfo.setText("Employee Info");
        add(lblCarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, -1, -1));

        lblID.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 0, 51));
        lblID.setText("EmpID:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, -1, 50));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 190, 50));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 0, 51));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/searching-2339723_1920.png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 50, -1));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 51));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/cancel.png"))); // NOI18N
        btnDelete.setToolTipText("Remove");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 50, 50));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 0, 51));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/add-1-icon.png"))); // NOI18N
        btnInsert.setToolTipText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 50, 50));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 51));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/5c8dd48504f17.png"))); // NOI18N
        btnReset.setToolTipText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, 50, 50));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 0, 51));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/24b70afe9c.png"))); // NOI18N
        btnUpdate.setToolTipText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 640, 50, 50));

        tblViewEmployee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblViewEmployee.setForeground(new java.awt.Color(0, 51, 255));
        tblViewEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "Name", "Sex", "Age", "Phone", "Certificate", "isAvailable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewEmployee.setRowHeight(24);
        tblViewEmployee.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblViewEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewEmployee);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 710, 520));

        pnlEmpInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmpInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        pnlEmpInfo.setForeground(new java.awt.Color(255, 51, 51));
        pnlEmpInfo.setPreferredSize(new java.awt.Dimension(51, 20));
        pnlEmpInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 51, 255));
        lblUsername.setText("EmpID:");
        pnlEmpInfo.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        txtEmpID.setEditable(false);
        txtEmpID.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtEmpID.setForeground(new java.awt.Color(0, 51, 255));
        txtEmpID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlEmpInfo.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 180, -1));

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPass.setForeground(new java.awt.Color(0, 51, 255));
        lblPass.setText("Fullname:");
        pnlEmpInfo.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 106, 28));

        lblSex.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSex.setForeground(new java.awt.Color(0, 51, 255));
        lblSex.setText("Age:");
        pnlEmpInfo.add(lblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 50));

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtAge.setForeground(new java.awt.Color(0, 51, 255));
        txtAge.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlEmpInfo.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 80, -1));

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 51, 255));
        lblAge.setText("Phone:");
        pnlEmpInfo.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 28));

        rdMale.setBackground(new java.awt.Color(255, 255, 255));
        groupSex.add(rdMale);
        rdMale.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdMale.setForeground(new java.awt.Color(0, 51, 255));
        rdMale.setSelected(true);
        rdMale.setText("Male");
        rdMale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEmpInfo.add(rdMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        rdFemale.setBackground(new java.awt.Color(255, 255, 255));
        groupSex.add(rdFemale);
        rdFemale.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdFemale.setForeground(new java.awt.Color(0, 51, 255));
        rdFemale.setText("Female");
        rdFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEmpInfo.add(rdFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(0, 51, 255));
        lblPhone.setText("Available:");
        pnlEmpInfo.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 28));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(0, 51, 255));
        txtPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlEmpInfo.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 180, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 51, 255));
        lblName.setText("Sex:");
        pnlEmpInfo.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 40));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtName.setForeground(new java.awt.Color(0, 51, 255));
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlEmpInfo.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 390, -1));

        msgName.setForeground(new java.awt.Color(255, 51, 51));
        pnlEmpInfo.add(msgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 390, 17));

        msgAge.setForeground(new java.awt.Color(255, 51, 51));
        pnlEmpInfo.add(msgAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 390, 17));

        msgPhone.setForeground(new java.awt.Color(255, 51, 51));
        pnlEmpInfo.add(msgPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 390, 14));

        rdTrue.setBackground(new java.awt.Color(255, 255, 255));
        groupAvailable.add(rdTrue);
        rdTrue.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdTrue.setForeground(new java.awt.Color(0, 51, 255));
        rdTrue.setSelected(true);
        rdTrue.setText("True");
        rdTrue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEmpInfo.add(rdTrue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        rdFalse.setBackground(new java.awt.Color(255, 255, 255));
        groupAvailable.add(rdFalse);
        rdFalse.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdFalse.setForeground(new java.awt.Color(0, 51, 255));
        rdFalse.setText("False");
        rdFalse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEmpInfo.add(rdFalse, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        lblCertificate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblCertificate.setForeground(new java.awt.Color(0, 51, 255));
        lblCertificate.setText("Certificate:");
        pnlEmpInfo.add(lblCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 50));

        spCertificate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spCertificate.setModel(new javax.swing.SpinnerNumberModel(2, 2, 100, 1));
        spCertificate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEmpInfo.add(spCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("MaxSeats");
        pnlEmpInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 437, -1, 40));

        add(pnlEmpInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 660, 520));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -80, 2660, 1220));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        EmpDAO empDAO = new EmpDAO();
        List<EmployeeDTO> result = null;
        if (txtSearch.getText().equals("")) {
            result = empDAO.findAllEmployees();
        } else {
            EmployeeDTO empDTO = empDAO.findByPrimaryKey(txtSearch.getText());
            if (empDTO != null) {
                result = new ArrayList<>();
                result.add(empDTO);
            }
        }
        if (result != null && !result.isEmpty()) {
            showEmployee(result);
        } else {
            JOptionPane.showMessageDialog(null, "Not Found!");
            tblModelEmployee.setRowCount(0);
        }
        btnDelete.setEnabled(false);
        btnReset.doClick();
        txtEmpID.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblViewEmployee.getSelectedRow();
            String empID = (String) tblModelEmployee.getValueAt(row, 0);
            EmpDAO empDAO = new EmpDAO();
            int dialogBtn = JOptionPane.showConfirmDialog(null, "Are you sure want to remove?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogBtn == JOptionPane.YES_OPTION) {
                if (empDAO.delete(empID)) {
                    JOptionPane.showMessageDialog(null, "Delete success");
                    btnDelete.setEnabled(false);
                    btnReset.doClick();
                    txtEmpID.setText("");
                    if (txtSearch.getText().equals("")) {
                        btnSearch.doClick();
                    } else {
                        tblModelEmployee.setRowCount(0);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Delete failed. This employee can be in some transactions");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select employee");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        new EmpInsertFrame(btnSearch, btnDelete, btnReset, txtSearch, txtEmpID).setVisible(true);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtPhone.setText("");
        txtAge.setText("");
        rdMale.setSelected(true);
        msgName.setText("");
        msgPhone.setText("");
        msgAge.setText("");
        rdTrue.setSelected(true);
        spCertificate.setValue(2);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        String empID = txtEmpID.getText();
        String fullname = txtName.getText();
        String phone = txtPhone.getText();
        boolean sex = rdMale.isSelected();
        boolean available = rdTrue.isSelected();
        int age = 0;
        int certificate = 0;
        try {
            age = Integer.parseInt(txtAge.getText());
        } catch (NumberFormatException e) {
        }
        try {
            certificate = (Integer) spCertificate.getValue();
        } catch (NumberFormatException e) {
        }
        EmpDAO empDAO = new EmpDAO();
        if (validate(empID, fullname, phone, age)) {
            int dialogBtn = JOptionPane.showConfirmDialog(null, "Are you sure want to save changes?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogBtn == JOptionPane.YES_OPTION) {
                if (empDAO.update(new EmployeeDTO(empID, fullname, phone, sex, available, age, certificate))) {
                    JOptionPane.showMessageDialog(null, "Update success");
                    btnDelete.setEnabled(false);
                    btnSearch.doClick();
                    btnReset.doClick();
                    txtEmpID.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Update failed");
                }
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblViewEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewEmployeeMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblViewEmployee.getSelectedRow();
            String empID = (String) tblModelEmployee.getValueAt(row, 0);
            loadEmployee(empID);
            btnDelete.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select employee");
        }
    }//GEN-LAST:event_tblViewEmployeeMouseClicked

    private void loadEmployee(String empID) {
        EmpDAO empDAO = new EmpDAO();
        EmployeeDTO empDTO = empDAO.findByPrimaryKey(empID);
        if (empDTO != null) {
            txtEmpID.setText(empDTO.getId());
            txtName.setText(empDTO.getName());
            if (empDTO.isSex()) {
                rdMale.setSelected(true);
            } else {
                rdFemale.setSelected(true);
            }
            txtAge.setText(Integer.toString(empDTO.getAge()));
            spCertificate.setValue(empDTO.getCertificate());
            txtPhone.setText(empDTO.getPhone());
            if (empDTO.isIsAvailable()) {
                rdTrue.setSelected(true);
            } else {
                rdFalse.setSelected(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cannot load employee information", "System warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private boolean validate(String empID, String fullname, String phone, int age) {
        boolean check = true;
        String phonePattern = "\\d{10}";
        if (empID.equals("")) {
            check = false;
            JOptionPane.showMessageDialog(null, "Please choose employee");
        } else {
            if (fullname.equals("")) {
                msgName.setText("Full name is not empty.");
                check = false;
            } else {
                msgName.setText("");
            }
            if (!phone.matches(phonePattern)) {
                msgPhone.setText("Phone is the sequence of 10 digits.");
                check = false;
            } else {
                msgPhone.setText("");
            }

            if (age < 1) {
                msgAge.setText("Age is a positive number");
                check = false;
            } else {
                msgAge.setText("");
            }
        }
        return check;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup groupAvailable;
    private javax.swing.ButtonGroup groupSex;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCarInfo;
    private javax.swing.JLabel lblCarList;
    private javax.swing.JLabel lblCertificate;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel msgAge;
    private javax.swing.JLabel msgName;
    private javax.swing.JLabel msgPhone;
    private javax.swing.JPanel pnlEmpInfo;
    private javax.swing.JRadioButton rdFalse;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JRadioButton rdTrue;
    private javax.swing.JSpinner spCertificate;
    private javax.swing.JTable tblViewEmployee;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
