/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin;

import anhht.gui.admin.insert.TransInsertFrame;
import anhht.daos.CustomerDAO;
import anhht.daos.TravelTransactionDAO;
import anhht.dtos.TravelTransactionDTO;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuana
 */
public class TransactionPanel extends javax.swing.JPanel {

    private DefaultTableModel tblModelTransaction = null;

    /**
     * Creates new form TransactionPanel
     */
    public TransactionPanel() {
        initComponents();
        tblModelTransaction = (DefaultTableModel) tblViewTransaction.getModel();
    }

    private void showTransaction(List<TravelTransactionDTO> list) {
        tblModelTransaction.setRowCount(0);
        for (TravelTransactionDTO travelTransactionDTO : list) {
            tblModelTransaction.addRow(travelTransactionDTO.toVector());
        }
    }

    private void loadTransaction(String key) {
        TravelTransactionDAO ttDAO = new TravelTransactionDAO();
        List<TravelTransactionDTO> result = ttDAO.findByCusID(key);
        if (!result.isEmpty()) {
            showTransaction(result);
        } else {
            JOptionPane.showMessageDialog(null, "Not found any transactions");
            tblModelTransaction.setRowCount(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTransList = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblViewTransaction = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTransList.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblTransList.setForeground(new java.awt.Color(255, 0, 0));
        lblTransList.setText("Transaction List");
        add(lblTransList, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        lblID.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 0, 0));
        lblID.setText("CusID:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, 50));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 0, 0));
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 640, 210, 50));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/searching-2339723_1920.png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 640, 50, 50));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/cancel.png"))); // NOI18N
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 640, 50, 50));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/add-1-icon.png"))); // NOI18N
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 640, 50, 50));

        tblViewTransaction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblViewTransaction.setForeground(new java.awt.Color(51, 51, 255));
        tblViewTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TransID", "CusID", "Destination", "Seats", "Car Serial", "Car Name", "Driver", "Start Time", "Duration (Hr)", "Price (VND)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewTransaction.setRowHeight(24);
        tblViewTransaction.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblViewTransaction.getTableHeader().setReorderingAllowed(false);
        tblViewTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewTransactionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblViewTransaction);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1420, 510));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 2660, 1220));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if (txtSearch.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter cusID");
            tblModelTransaction.setRowCount(0);
        } else {
            loadTransaction(txtSearch.getText());
        }
        btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            boolean check = true;
            int row = tblViewTransaction.getSelectedRow();
            String transID = (String) tblModelTransaction.getValueAt(row, 0);
            int dialogBtn = JOptionPane.showConfirmDialog(null, "Are you sure want to remove?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogBtn == JOptionPane.YES_OPTION) {
                TravelTransactionDAO ttDAO = new TravelTransactionDAO();
                TravelTransactionDTO ttDTO = ttDAO.findByPrimaryKey(transID);
                Timestamp currentTime = new Timestamp(new Date().getTime());
                if (currentTime.getTime() > ttDTO.getStartTime().getTime() - 3 * 3600000) {
                    int dialogBtn2 = JOptionPane.showConfirmDialog(null, "This transaction has been processed or it's too late to cancel transation. Do you want to continue?",
                            "Warning", JOptionPane.YES_NO_OPTION);
                    if (dialogBtn2 == JOptionPane.YES_OPTION) {
                        check = true;
                    } else {
                        check = false;
                    }
                }
                if (check) {
                    if (ttDAO.delete(transID)) {
                        JOptionPane.showMessageDialog(null, "Delete success");
                        btnDelete.setEnabled(false);
                        btnSearch.doClick();
                    } else {
                        JOptionPane.showMessageDialog(null, "Delete failed");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select transaction");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        String cusID = txtSearch.getText();
        if (!cusID.equals("")) {
            CustomerDAO cusDAO = new CustomerDAO();
            if (cusDAO.findExisting(cusID)) {
                new TransInsertFrame(cusID, btnSearch, btnDelete, tblModelTransaction).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "CusID not found!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter CusID");
        }

    }//GEN-LAST:event_btnInsertActionPerformed

    private void tblViewTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewTransactionMouseClicked
        // TODO add your handling code here:
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblViewTransactionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTransList;
    private javax.swing.JTable tblViewTransaction;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
