/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin;

import anhht.gui.admin.insert.TravelPriceInsertFrame;
import anhht.daos.CarCategoryDAO;
import anhht.daos.TravelPriceDAO;
import anhht.dtos.CarCategoryDTO;
import anhht.dtos.TravelPriceDTO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tuana
 */
public class TravelPricePanel extends javax.swing.JPanel {

    private DefaultTableModel tblModelTravelPrice = null;

    /**
     * Creates new form TravelPricePanel
     */
    public TravelPricePanel() {
        initComponents();
        tblModelTravelPrice = (DefaultTableModel) tblViewTravelPrice.getModel();
        loadCbCarCategory();
        ((JSpinner.DefaultEditor) spLimitTime.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) spDistance.getEditor()).getTextField().setEditable(false);
    }

    private void loadCbCarCategory() {
        CarCategoryDAO carCateDAO = new CarCategoryDAO();
        List<CarCategoryDTO> result = carCateDAO.findAll();
        for (CarCategoryDTO carCategoryDTO : result) {
            cbSeats.addItem(Integer.toString(carCategoryDTO.getNumberOfSeats()));
        }
    }

    private void showTravelPrice(List<TravelPriceDTO> list) {
        tblModelTravelPrice.setRowCount(0);
        for (TravelPriceDTO travelPriceDTO : list) {
            tblModelTravelPrice.addRow(travelPriceDTO.toVector());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewTravelPrice = new javax.swing.JTable();
        lblID = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        lblCarInfo = new javax.swing.JLabel();
        pnlTravelPriceInfo = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtTravelID = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        msgDes = new javax.swing.JLabel();
        msgPrice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spLimitTime = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cbSeats = new javax.swing.JComboBox<>();
        spDistance = new javax.swing.JSpinner();
        txtDestination = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarList.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarList.setForeground(new java.awt.Color(255, 0, 0));
        lblCarList.setText("Travel Price List");
        add(lblCarList, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        tblViewTravelPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblViewTravelPrice.setForeground(new java.awt.Color(51, 51, 255));
        tblViewTravelPrice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TravelID", "Destination", "Limit Time (Hr)", "EstDistance (Km)", "Seats", "Price (VND)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewTravelPrice.setRowHeight(24);
        tblViewTravelPrice.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblViewTravelPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewTravelPriceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewTravelPrice);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 800, 520));

        lblID.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 0, 0));
        lblID.setText("Destination:");
        add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, 50));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(255, 0, 0));
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 640, 170, 50));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 0, 0));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/searching-2339723_1920.png"))); // NOI18N
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 50, 50));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 0, 0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/cancel.png"))); // NOI18N
        btnDelete.setToolTipText("Remove");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, 50, 50));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(255, 0, 0));
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/add-1-icon.png"))); // NOI18N
        btnInsert.setToolTipText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, 50, 50));

        lblCarInfo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarInfo.setForeground(new java.awt.Color(255, 0, 0));
        lblCarInfo.setText("Travel Price Info");
        add(lblCarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, -1, 40));

        pnlTravelPriceInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlTravelPriceInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        pnlTravelPriceInfo.setForeground(new java.awt.Color(255, 51, 51));
        pnlTravelPriceInfo.setPreferredSize(new java.awt.Dimension(51, 20));
        pnlTravelPriceInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 51, 255));
        lblUsername.setText("TravelID:");
        pnlTravelPriceInfo.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 31, -1, 30));

        txtTravelID.setEditable(false);
        txtTravelID.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtTravelID.setForeground(new java.awt.Color(51, 51, 255));
        txtTravelID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlTravelPriceInfo.add(txtTravelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 160, -1));

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPass.setForeground(new java.awt.Color(51, 51, 255));
        lblPass.setText("Destination:");
        pnlTravelPriceInfo.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 120, 28));

        lblSex.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSex.setForeground(new java.awt.Color(51, 51, 255));
        lblSex.setText("Est. Distance:");
        pnlTravelPriceInfo.add(lblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 257, -1, 50));

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblAge.setForeground(new java.awt.Color(51, 51, 255));
        lblAge.setText("Number Of Seats:");
        pnlTravelPriceInfo.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 365, -1, 28));

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(51, 51, 255));
        lblPhone.setText("Price:");
        pnlTravelPriceInfo.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 451, -1, 28));

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(51, 51, 255));
        txtPrice.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlTravelPriceInfo.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 449, 170, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 51, 255));
        lblName.setText("Limit Time:");
        pnlTravelPriceInfo.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 186, -1, 28));

        msgDes.setForeground(new java.awt.Color(255, 51, 51));
        pnlTravelPriceInfo.add(msgDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 149, 386, 20));

        msgPrice.setForeground(new java.awt.Color(255, 51, 51));
        pnlTravelPriceInfo.add(msgPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 491, 183, 14));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Hours");
        pnlTravelPriceInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, 30));

        spLimitTime.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spLimitTime.setModel(new javax.swing.SpinnerNumberModel(1, 1, 120, 1));
        spLimitTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTravelPriceInfo.add(spLimitTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("VND");
        pnlTravelPriceInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, 30));

        cbSeats.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cbSeats.setForeground(new java.awt.Color(51, 51, 255));
        cbSeats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTravelPriceInfo.add(cbSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        spDistance.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spDistance.setModel(new javax.swing.SpinnerNumberModel(10, 10, 1000, 10));
        spDistance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlTravelPriceInfo.add(spDistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        txtDestination.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtDestination.setForeground(new java.awt.Color(51, 51, 255));
        pnlTravelPriceInfo.add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 300, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Km");
        pnlTravelPriceInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, 30));

        add(pnlTravelPriceInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, 570, 530));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 0, 0));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/5c8dd48504f17.png"))); // NOI18N
        btnReset.setToolTipText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 650, 50, 50));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 0, 0));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/24b70afe9c.png"))); // NOI18N
        btnUpdate.setToolTipText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 650, 50, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 2660, 1220));
    }// </editor-fold>//GEN-END:initComponents

    private void tblViewTravelPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewTravelPriceMouseClicked
        // TODO add your handling code here:
        try {
            int row = tblViewTravelPrice.getSelectedRow();
            String travelID = (String) tblModelTravelPrice.getValueAt(row, 0);
            loadTravelPrice(travelID);
            btnDelete.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select travel price");
        }
    }//GEN-LAST:event_tblViewTravelPriceMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        TravelPriceDAO tpDAO = new TravelPriceDAO();
        List<TravelPriceDTO> result = null;
        if (txtSearch.getText().equals("")) {
            result = tpDAO.findAll();
        } else {
            result = tpDAO.findByDestination(txtSearch.getText());
        }
        if (result != null && !result.isEmpty()) {
            showTravelPrice(result);
        } else {
            JOptionPane.showMessageDialog(null, "Not Found!");
            tblModelTravelPrice.setRowCount(0);
        }
        btnDelete.setEnabled(false);
        btnReset.doClick();
        txtTravelID.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblViewTravelPrice.getSelectedRow();
            String travelID = (String) tblModelTravelPrice.getValueAt(row, 0);
            TravelPriceDAO tpDAO = new TravelPriceDAO();
            int dialogBtn = JOptionPane.showConfirmDialog(null, "Are you sure want to remove?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogBtn == JOptionPane.YES_OPTION) {
                if (tpDAO.delete(travelID)) {
                    JOptionPane.showMessageDialog(null, "Delete success");
                    btnDelete.setEnabled(false);
                    btnReset.doClick();
                    txtTravelID.setText("");
                    if (txtSearch.getText().equals("")) {
                        btnSearch.doClick();
                    } else {
                        tblModelTravelPrice.setRowCount(0);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Delete failed. This travel price can be in some transactions.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select travel price");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        new TravelPriceInsertFrame(btnSearch, btnDelete, btnReset, txtSearch, txtTravelID).setVisible(true);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtDestination.setText("");
        msgDes.setText("");
        spLimitTime.setValue(1);
        spDistance.setValue(10);
        txtPrice.setText("");
        msgDes.setText("");
        msgPrice.setText("");
        cbSeats.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        String travelID = txtTravelID.getText();
        String des = txtDestination.getText();
        int limitTime = (Integer) spLimitTime.getValue();
        int distance = (Integer) spDistance.getValue();
        int seats = Integer.parseInt((String) cbSeats.getSelectedItem());
        int price = 0;
        try {
            price = Integer.parseInt(txtPrice.getText());
        } catch (NumberFormatException e) {
        }
        TravelPriceDAO tpDAO = new TravelPriceDAO();
        if (validate(travelID, des, price)) {
            int dialogBtn = JOptionPane.showConfirmDialog(null, "Are you sure want to save changes?", "Warning", JOptionPane.YES_NO_OPTION);
            if (dialogBtn == JOptionPane.YES_OPTION) {
                if (tpDAO.update(new TravelPriceDTO(travelID, des, limitTime, distance, seats, price))) {
                    JOptionPane.showMessageDialog(null, "Update success");
                    btnDelete.setEnabled(false);
                    btnSearch.doClick();
                    btnReset.doClick();
                    txtTravelID.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Update failed");
                }
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private boolean validate(String travelID, String destination, int price) {
        boolean check = true;
        if (travelID.equals("")) {
            check = false;
            JOptionPane.showMessageDialog(null, "Please choose travel price");
        } else {
            if (destination.equals("")) {
                msgDes.setText("Destination is not empty");
                check = false;
            } else {
                msgDes.setText("");
            }
            if (price < 1) {
                msgPrice.setText("Price is a positive number");
                check = false;
            } else {
                msgPrice.setText("");
            }
        }
        return check;
    }

    private void loadTravelPrice(String travelID) {
        TravelPriceDAO tpDAO = new TravelPriceDAO();
        TravelPriceDTO tpDTO = tpDAO.findByPrimaryKey(travelID);
        if (tpDTO != null) {
            txtTravelID.setText(tpDTO.getId());
            txtDestination.setText(tpDTO.getDestination());
            spLimitTime.setValue(tpDTO.getLimitTime());
            spDistance.setValue(tpDTO.getEstDistance());
            cbSeats.setSelectedItem(Integer.toString(tpDTO.getNumberOfSeats()));
            txtPrice.setText(Integer.toString(tpDTO.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Cannot load travel price information", "System warning", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbSeats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCarInfo;
    private javax.swing.JLabel lblCarList;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel msgDes;
    private javax.swing.JLabel msgPrice;
    private javax.swing.JPanel pnlTravelPriceInfo;
    private javax.swing.JSpinner spDistance;
    private javax.swing.JSpinner spLimitTime;
    private javax.swing.JTable tblViewTravelPrice;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTravelID;
    // End of variables declaration//GEN-END:variables
}
