//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.30 at 12:09:25 AM ICT 
//
package anhht.entity;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 */
@Entity
@Table(name = "TblAccount")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "username",
    "fullname",
    "password"
})
@XmlRootElement(name = "account")
public class Account implements Serializable {

    @Id
    @Column(name = "Username", nullable = false)
    @XmlElement(required = true)
    protected String username;

    @Column(name = "Fullname", nullable = false)
    @XmlElement(required = true)
    protected String fullname;
    
    @Column(name = "Password", nullable = false)
    @XmlElement(required = true)
    protected String password;

    /**
     * Gets the value of the username property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the fullname property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFullname(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the password property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPassword(String value) {
        this.password = value;
    }

}
