/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popem.views;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import popem.daos.AccountDAO;
import popem.daos.ClassDAO;
import popem.daos.InventoryDAO;
import popem.dtos.ClassDTO;
import popem.dtos.InventoryDTO;

/**
 *
 * @author popem
 */
public class CharacterCreationPanel extends javax.swing.JPanel {
    JLabel lblCharacterAvatar;
    JLabel lblCharacterAvatarBG;
    JPanel parent;
    String username;
    UserFrame userFrame;
    
    /**
     * Creates new form CharacterCreationFrame
     */
    public CharacterCreationPanel(String username, UserFrame userFrame) {
        initComponents();
        this.lblCharacterAvatar = userFrame.getLblCharacterAvatar();
        this.lblCharacterAvatarBG = userFrame.getLblCharacterAvatarBG();
        this.username = username;
        this.parent = userFrame.getPnlMain();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAccountUpdate = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMissionItemDes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCharacterName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbClass = new javax.swing.JComboBox<>();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAccountUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnAccountUpdate.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 1, 36)); // NOI18N
        btnAccountUpdate.setForeground(new java.awt.Color(204, 51, 0));
        btnAccountUpdate.setText("CREATE");
        btnAccountUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 1, new java.awt.Color(0, 0, 0)));
        btnAccountUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountUpdateActionPerformed(evt);
            }
        });
        add(btnAccountUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 530, 70));

        jScrollPane4.setBorder(null);

        txtMissionItemDes.setBackground(new java.awt.Color(230, 230, 230));
        txtMissionItemDes.setColumns(20);
        txtMissionItemDes.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        txtMissionItemDes.setForeground(new java.awt.Color(0, 102, 102));
        txtMissionItemDes.setLineWrap(true);
        txtMissionItemDes.setRows(5);
        txtMissionItemDes.setText("Mystical human-like race who excels at magic. Lifespan of approximately 1 millennia. Has passive of extending mission time to 1,5x normal.");
        txtMissionItemDes.setWrapStyleWord(true);
        txtMissionItemDes.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 204, 204))));
        jScrollPane4.setViewportView(txtMissionItemDes);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 530, 140));

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Class Description");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Character Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        txtCharacterName.setBackground(new java.awt.Color(230, 230, 230));
        txtCharacterName.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtCharacterName.setForeground(new java.awt.Color(0, 102, 102));
        txtCharacterName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createMatteBorder(0, 15, 0, 0, new java.awt.Color(230, 230, 230))));
        txtCharacterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCharacterNameActionPerformed(evt);
            }
        });
        add(txtCharacterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 530, 60));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Class");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, -1));

        cbClass.setBackground(new java.awt.Color(0, 51, 255));
        cbClass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbClass.setForeground(new java.awt.Color(0, 102, 102));
        cbClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elf", "Mecha", "Demon", "Human" }));
        cbClass.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 10, 0, 0, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(0, 20, 0, 0, new java.awt.Color(204, 204, 204))));
        cbClass.setOpaque(false);
        cbClass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClassItemStateChanged(evt);
            }
        });
        add(cbClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCharacterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCharacterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCharacterNameActionPerformed

    private void btnAccountUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountUpdateActionPerformed
        // TODO add your handling code here:
        boolean check = false;
        String validate = "";
        if (!txtCharacterName.getText().matches("\\w{6,12}")) validate += "Character name must be between 6-12 characters!\n";
        if (!validate.equals("")) JOptionPane.showMessageDialog(this, validate);
        else {
            try {
                check = new AccountDAO().updateCharacterCreation(username, txtCharacterName.getText(), cbClass.getSelectedItem().toString());
                ClassDTO classDTO = new ClassDAO().findByPrimaryKey(cbClass.getSelectedItem().toString());
                if (check) {
                    if (classDTO.getName().equals("Mecha")) {
                        InventoryDAO inventoryDAO = new InventoryDAO();
                        inventoryDAO.create(new InventoryDTO(username, "I05", 5));
                    } else if (classDTO.getName().equals("Human")) {
                        InventoryDAO inventoryDAO = new InventoryDAO();
                        inventoryDAO.create(new InventoryDTO(username, "I03", 1));
                    }
                    JOptionPane.showMessageDialog(this, "Create Successful!");
                    parent.removeAll();
                    parent.add(new PlayingPanel(username, classDTO, userFrame));
                    JOptionPane.showMessageDialog(parent, "You are now ready to Play!\nEnjoy the World of OASIS!");
                    parent.updateUI();
                }
                else JOptionPane.showMessageDialog(this, "Create failed!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Create failed!");
            }
        }
    }//GEN-LAST:event_btnAccountUpdateActionPerformed

    private void cbClassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClassItemStateChanged
        // TODO add your handling code here:
        String className = cbClass.getSelectedItem().toString();
        lblCharacterAvatar.setIcon(new ImageIcon(getClass().getResource("/popem/img/"+className+".png")));
        lblCharacterAvatarBG.setIcon(new ImageIcon(getClass().getResource("/popem/img/"+className+"_bg.png")));
        try {
            ClassDAO classDAO = new ClassDAO();
            ClassDTO classDTO = classDAO.findByPrimaryKey(className);
            txtMissionItemDes.setText(classDTO.getDescription());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cbClassItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountUpdate;
    private javax.swing.JComboBox<String> cbClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField txtCharacterName;
    private javax.swing.JTextArea txtMissionItemDes;
    // End of variables declaration//GEN-END:variables
}
