/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popem.views;

import java.awt.Color;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import popem.daos.AccountDAO;
import popem.daos.ClassDAO;
import popem.daos.CompletedMissionDAO;
import popem.daos.InventoryDAO;
import popem.daos.ItemDAO;
import popem.daos.MissionDAO;
import popem.dtos.AccountDTO;
import popem.dtos.ClassDTO;
import popem.dtos.CompletedMissionDTO;
import popem.dtos.InventoryDTO;
import popem.dtos.ItemDTO;
import popem.dtos.MissionDTO;
import popem.gameplay.GameplayManager;

/**
 *
 * @author popem
 */
public class PlayingPanel extends javax.swing.JPanel {
    DefaultTableModel tblModelAccountInventory;
    DefaultTableModel tblModelCompletedMission;
    DefaultTableModel tblModelMission;
    DefaultTableModel tblModelLeaderboard;
    UserFrame userFrame;
    ClassDTO classDTO;
    AccountDTO accountDTO;
    List<InventoryDTO> inventoryDTOs;
    ItemDTO currentItem = new ItemDTO();
    GameplayManager gameplayManager;
    
    /**
     * Creates new form PlayingPanel
     */
    public PlayingPanel(String username, ClassDTO classDTO, UserFrame userFrame) {
        initComponents();
        tblModelAccountInventory = (DefaultTableModel)tblAccountInventory.getModel();
        tblModelCompletedMission = (DefaultTableModel)tblCompletedMission.getModel();
        tblModelMission = (DefaultTableModel)tblMission.getModel();
        tblModelLeaderboard = (DefaultTableModel)tblLeaderboard.getModel();
        this.userFrame = userFrame;
        try {
            this.classDTO = classDTO;
            accountDTO = new AccountDAO().findByPrimaryKey(username);
            inventoryDTOs = new InventoryDAO().findByUsername(username);
            loadCbItem();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Load Item failed!");
        }
        btnPlay.setVisible(false);
        jTabbedPane1.setEnabledAt(1, false);
    }
    
    private void loadMission(List<MissionDTO> list) throws Exception{
        tblModelMission.setRowCount(0);
        for (MissionDTO dto : list){
            tblModelMission.addRow(dto.toVector());
        }
    }
    
    private void loadCompletedMission(List<CompletedMissionDTO> list) throws Exception{
        CompletedMissionDAO cmDAO = new CompletedMissionDAO();
        MissionDAO mDAO = new MissionDAO();
        Vector temp;
        String missionName;
        tblModelCompletedMission.setRowCount(0);
        for (CompletedMissionDTO cmDTO : list){
            temp = cmDTO.toVector();
            missionName = mDAO.findByPrimaryKey(cmDTO.getMission()).getName();
            temp.set(1, missionName);
            tblModelCompletedMission.addRow(temp);
        }
    }
    
    private void loadInventory(List<InventoryDTO> list){
        tblModelAccountInventory.setRowCount(0);
        for (InventoryDTO item : list){
            tblModelAccountInventory.addRow(item.toVector());
        }
    }
    
    private void loadCbItem() throws Exception{
        ItemDAO dao = new ItemDAO();
        cbMissionItem.removeAllItems();
        cbMissionItem.addItem("None");
        for (InventoryDTO dto : inventoryDTOs){
            if (!dto.getItem().matches("I0[1-3]")){
                String string = dto.getItem()+"-"+dao.findByPrimaryKey(dto.getItem()).getName();
                cbMissionItem.addItem(string); 
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlMissionChooser = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMission = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnSearchMission = new javax.swing.JButton();
        cbSearchMission = new javax.swing.JComboBox<>();
        txtSearchMission = new javax.swing.JTextField();
        lblDes = new javax.swing.JLabel();
        lblItem = new javax.swing.JLabel();
        cbMissionItem = new javax.swing.JComboBox<>();
        lblRemaining = new javax.swing.JLabel();
        txtWarning = new javax.swing.JLabel();
        pnlPlay = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMissionQuestion = new javax.swing.JTextArea();
        pbTemp = new javax.swing.JProgressBar();
        rdChoice1 = new javax.swing.JRadioButton();
        rdChoice2 = new javax.swing.JRadioButton();
        rdChoice3 = new javax.swing.JRadioButton();
        txtMissionAnswer = new javax.swing.JTextField();
        pbOverall = new javax.swing.JProgressBar();
        btnFinish = new javax.swing.JButton();
        lblHint = new javax.swing.JLabel();
        pnlRanking = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLeaderboard = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        User = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAccountUsername = new javax.swing.JTextField();
        imgAccountClass = new javax.swing.JLabel();
        txtAccountCharName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cbAccountRank = new javax.swing.JComboBox<>();
        cbAccountCharacterClass = new javax.swing.JComboBox<>();
        txtAccountPoints = new javax.swing.JTextField();
        txtAccountPassword = new javax.swing.JPasswordField();
        cbAccountRole = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblItemInventoryDes = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAccountInventory = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        btnAccountUpdate = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblCompletedMission = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        lblClassDes = new javax.swing.JLabel();
        lblDesDropRate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 153));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTabbedPane1ComponentShown(evt);
            }
        });
        jTabbedPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTabbedPane1PropertyChange(evt);
            }
        });

        pnlMissionChooser.setOpaque(false);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        tblMission.setBackground(new java.awt.Color(240, 240, 240));
        tblMission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Rank", "Reward"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMission.setOpaque(false);
        tblMission.setShowVerticalLines(false);
        tblMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMissionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMission);
        if (tblMission.getColumnModel().getColumnCount() > 0) {
            tblMission.getColumnModel().getColumn(0).setResizable(false);
            tblMission.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblMission.getColumnModel().getColumn(1).setResizable(false);
            tblMission.getColumnModel().getColumn(2).setResizable(false);
            tblMission.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblMission.getColumnModel().getColumn(3).setResizable(false);
            tblMission.getColumnModel().getColumn(3).setPreferredWidth(70);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Mission");

        btnPlay.setBackground(new java.awt.Color(255, 255, 255));
        btnPlay.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(51, 51, 51));
        btnPlay.setText("PLAY");
        btnPlay.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2), javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/popem/img/Border.png"))))); // NOI18N
        btnPlay.setContentAreaFilled(false);
        btnPlay.setMargin(new java.awt.Insets(20, 14, 20, 14));
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlayMouseExited(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnSearchMission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/popem/img/Search.png"))); // NOI18N
        btnSearchMission.setBorder(null);
        btnSearchMission.setContentAreaFilled(false);
        btnSearchMission.setFocusPainted(false);
        btnSearchMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMissionActionPerformed(evt);
            }
        });

        cbSearchMission.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Name", "Question", "Item", "Rank" }));
        cbSearchMission.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 1, new java.awt.Color(204, 204, 204)));
        cbSearchMission.setFocusable(false);

        txtSearchMission.setBackground(new java.awt.Color(204, 204, 204));
        txtSearchMission.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearchMission.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(204, 204, 204))));
        txtSearchMission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchMissionActionPerformed(evt);
            }
        });

        lblDes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblItem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblItem.setForeground(new java.awt.Color(51, 51, 51));
        lblItem.setText("Item");

        cbMissionItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        cbMissionItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 1, new java.awt.Color(204, 204, 204)));
        cbMissionItem.setFocusable(false);
        cbMissionItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMissionItemItemStateChanged(evt);
            }
        });
        cbMissionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMissionItemActionPerformed(evt);
            }
        });

        txtWarning.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txtWarning.setForeground(new java.awt.Color(204, 0, 0));
        txtWarning.setText(" ");
        txtWarning.setToolTipText("");

        javax.swing.GroupLayout pnlMissionChooserLayout = new javax.swing.GroupLayout(pnlMissionChooser);
        pnlMissionChooser.setLayout(pnlMissionChooserLayout);
        pnlMissionChooserLayout.setHorizontalGroup(
            pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMissionChooserLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMissionChooserLayout.createSequentialGroup()
                        .addGroup(pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMissionChooserLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSearchMission, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSearchMission, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchMission, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMissionChooserLayout.createSequentialGroup()
                        .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMissionChooserLayout.createSequentialGroup()
                                .addComponent(lblItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMissionItem, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDes, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(pnlMissionChooserLayout.createSequentialGroup()
                        .addComponent(txtWarning)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlMissionChooserLayout.setVerticalGroup(
            pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMissionChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbSearchMission)
                        .addComponent(btnSearchMission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearchMission, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMissionChooserLayout.createSequentialGroup()
                        .addGroup(pnlMissionChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMissionChooserLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblItem))
                            .addComponent(cbMissionItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDes, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MISSON", pnlMissionChooser);

        pnlPlay.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Question");

        jScrollPane1.setBorder(null);

        txtMissionQuestion.setColumns(20);
        txtMissionQuestion.setFont(new java.awt.Font("MS PGothic", 1, 24)); // NOI18N
        txtMissionQuestion.setForeground(new java.awt.Color(0, 102, 102));
        txtMissionQuestion.setLineWrap(true);
        txtMissionQuestion.setRows(5);
        txtMissionQuestion.setText("asdfadsfasdfasdfasdfasdf");
        txtMissionQuestion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtMissionQuestion);

        pbTemp.setString("");
        pbTemp.setStringPainted(true);

        rdChoice1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdChoice1);
        rdChoice1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdChoice1.setForeground(new java.awt.Color(0, 51, 102));

        rdChoice2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdChoice2);
        rdChoice2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdChoice2.setForeground(new java.awt.Color(0, 51, 102));

        rdChoice3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdChoice3);
        rdChoice3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        rdChoice3.setForeground(new java.awt.Color(0, 51, 102));

        txtMissionAnswer.setBackground(new java.awt.Color(204, 204, 204));
        txtMissionAnswer.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 204, 204))));
        txtMissionAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMissionAnswerActionPerformed(evt);
            }
        });

        pbOverall.setString("");
        pbOverall.setStringPainted(true);

        btnFinish.setBackground(new java.awt.Color(255, 255, 255));
        btnFinish.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        btnFinish.setForeground(new java.awt.Color(51, 51, 51));
        btnFinish.setText("FINISH");
        btnFinish.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2), javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new javax.swing.ImageIcon(getClass().getResource("/popem/img/Border.png"))))); // NOI18N
        btnFinish.setContentAreaFilled(false);
        btnFinish.setMargin(new java.awt.Insets(20, 14, 20, 14));
        btnFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFinishMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFinishMouseExited(evt);
            }
        });
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        lblHint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHint.setForeground(new java.awt.Color(255, 51, 0));
        lblHint.setText(" ");

        javax.swing.GroupLayout pnlPlayLayout = new javax.swing.GroupLayout(pnlPlay);
        pnlPlay.setLayout(pnlPlayLayout);
        pnlPlayLayout.setHorizontalGroup(
            pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdChoice1)
                    .addComponent(rdChoice3)
                    .addComponent(rdChoice2)
                    .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pbOverall, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                        .addComponent(lblHint)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGroup(pnlPlayLayout.createSequentialGroup()
                            .addComponent(txtMissionAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pbTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pnlPlayLayout.setVerticalGroup(
            pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pbOverall, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHint)
                .addGap(7, 7, 7)
                .addComponent(rdChoice1)
                .addGap(18, 18, 18)
                .addComponent(rdChoice2)
                .addGap(18, 18, 18)
                .addComponent(rdChoice3)
                .addGap(18, 18, 18)
                .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMissionAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PLAY", pnlPlay);

        pnlRanking.setOpaque(false);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        tblLeaderboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Character Name", "Rank", "Class", "Points", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLeaderboard.setOpaque(false);
        tblLeaderboard.setShowHorizontalLines(false);
        tblLeaderboard.setShowVerticalLines(false);
        tblLeaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLeaderboardMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLeaderboard);
        if (tblLeaderboard.getColumnModel().getColumnCount() > 0) {
            tblLeaderboard.getColumnModel().getColumn(0).setResizable(false);
            tblLeaderboard.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblLeaderboard.getColumnModel().getColumn(1).setResizable(false);
            tblLeaderboard.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblLeaderboard.getColumnModel().getColumn(2).setResizable(false);
            tblLeaderboard.getColumnModel().getColumn(3).setResizable(false);
            tblLeaderboard.getColumnModel().getColumn(4).setResizable(false);
            tblLeaderboard.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Leaderboard");

        javax.swing.GroupLayout pnlRankingLayout = new javax.swing.GroupLayout(pnlRanking);
        pnlRanking.setLayout(pnlRankingLayout);
        pnlRankingLayout.setHorizontalGroup(
            pnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRankingLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnlRankingLayout.setVerticalGroup(
            pnlRankingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRankingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RANKING", pnlRanking);

        User.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("User Info");

        txtAccountUsername.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 204, 204))));
        txtAccountUsername.setEnabled(false);
        txtAccountUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountUsernameActionPerformed(evt);
            }
        });

        txtAccountCharName.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountCharName.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 204, 204))));
        txtAccountCharName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountCharNameActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Class");

        cbAccountRank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Champion", "Veteran", "Rookie" }));
        cbAccountRank.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 1, new java.awt.Color(102, 102, 102)));
        cbAccountRank.setEnabled(false);
        cbAccountRank.setMinimumSize(new java.awt.Dimension(67, 22));
        cbAccountRank.setPreferredSize(new java.awt.Dimension(67, 22));
        cbAccountRank.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAccountRankItemStateChanged(evt);
            }
        });
        cbAccountRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAccountRankActionPerformed(evt);
            }
        });
        cbAccountRank.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbAccountRankPropertyChange(evt);
            }
        });

        cbAccountCharacterClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mecha", "Elf", "Human", "Demon" }));
        cbAccountCharacterClass.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 1, new java.awt.Color(204, 204, 204)));
        cbAccountCharacterClass.setFocusable(false);
        cbAccountCharacterClass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAccountCharacterClassItemStateChanged(evt);
            }
        });
        cbAccountCharacterClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbAccountCharacterClassMouseClicked(evt);
            }
        });

        txtAccountPoints.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountPoints.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 204, 204))));
        txtAccountPoints.setEnabled(false);
        txtAccountPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccountPointsActionPerformed(evt);
            }
        });

        txtAccountPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtAccountPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 7, 0, 0, new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(204, 204, 204))));
        txtAccountPassword.setEnabled(false);

        cbAccountRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user" }));
        cbAccountRole.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 1, new java.awt.Color(102, 102, 102)));
        cbAccountRole.setEnabled(false);
        cbAccountRole.setMinimumSize(new java.awt.Dimension(67, 22));
        cbAccountRole.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAccountRoleItemStateChanged(evt);
            }
        });
        cbAccountRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAccountRoleActionPerformed(evt);
            }
        });
        cbAccountRole.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbAccountRolePropertyChange(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Username");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Password");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Rank");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Points");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Character Name");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Role");

        lblItemInventoryDes.setText(" ");

        lblItemName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(51, 51, 51));
        lblItemName.setText("Item");

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 0, 0, new java.awt.Color(102, 102, 102)));

        tblAccountInventory.setBackground(new java.awt.Color(204, 204, 204));
        tblAccountInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAccountInventory.setOpaque(false);
        tblAccountInventory.setShowHorizontalLines(false);
        tblAccountInventory.setShowVerticalLines(false);
        tblAccountInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAccountInventoryMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblAccountInventory);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Inventory");

        btnAccountUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAccountUpdate.setForeground(new java.awt.Color(0, 153, 0));
        btnAccountUpdate.setText("UPDATE");
        btnAccountUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 7, 1, 1, new java.awt.Color(0, 0, 0)));
        btnAccountUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountUpdateActionPerformed(evt);
            }
        });

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 0, 0, 0, new java.awt.Color(102, 102, 102)));

        tblCompletedMission.setBackground(new java.awt.Color(204, 204, 204));
        tblCompletedMission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Highest_Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompletedMission.setOpaque(false);
        tblCompletedMission.setShowHorizontalLines(false);
        tblCompletedMission.setShowVerticalLines(false);
        tblCompletedMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCompletedMissionMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblCompletedMission);
        if (tblCompletedMission.getColumnModel().getColumnCount() > 0) {
            tblCompletedMission.getColumnModel().getColumn(0).setResizable(false);
            tblCompletedMission.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblCompletedMission.getColumnModel().getColumn(1).setResizable(false);
            tblCompletedMission.getColumnModel().getColumn(2).setResizable(false);
            tblCompletedMission.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Completed Missons");

        lblClassDes.setText(" ");

        lblDesDropRate.setText(" ");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 6)); // NOI18N
        jButton1.setText("CHANGE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserLayout.createSequentialGroup()
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UserLayout.createSequentialGroup()
                                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imgAccountClass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAccountCharName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(UserLayout.createSequentialGroup()
                                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel20)
                                                    .addComponent(txtAccountPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbAccountRank, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel21)))
                                            .addComponent(txtAccountUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18)
                                            .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UserLayout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jButton1))
                                                .addComponent(txtAccountPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItemName)
                                    .addComponent(lblItemInventoryDes, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDesDropRate)))
                            .addComponent(jLabel3)
                            .addGroup(UserLayout.createSequentialGroup()
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAccountUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(UserLayout.createSequentialGroup()
                                            .addGap(196, 196, 196)
                                            .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel24)
                                                .addComponent(cbAccountRole, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(lblClassDes))
                                .addGap(26, 26, 26)
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbAccountCharacterClass, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbAccountCharacterClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addComponent(imgAccountClass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel24)))
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAccountUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jButton1))
                                .addGap(3, 3, 3)
                                .addComponent(txtAccountPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbAccountRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAccountPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(jLabel23))
                            .addGroup(UserLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblItemName)
                                .addGap(1, 1, 1)
                                .addComponent(lblItemInventoryDes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDesDropRate)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UserLayout.createSequentialGroup()
                        .addGroup(UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAccountCharName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAccountRole, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblClassDes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAccountUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("USER", User);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 740, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void tblMissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMissionMouseClicked
            // TODO add your handling code here:
        int row = tblMission.getSelectedRow();
        btnPlay.setVisible(true);
        try {
            CompletedMissionDAO cmDAO = new CompletedMissionDAO();
            CompletedMissionDTO cmDTO = cmDAO.findByPrimaryKey(accountDTO.getUsername(), tblModelMission.getValueAt(row, 0).toString());
            if (cmDTO != null) txtWarning.setText("On completed missions, you get extremely low rewards! ");
            else txtWarning.setText(" ");
        } catch (Exception ex) {
            Logger.getLogger(PlayingPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMissionMouseClicked

    private void btnPlayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseEntered
        // TODO add your handling code here:
        btnPlay.setContentAreaFilled(true);
        btnPlay.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnPlayMouseEntered

    private void btnPlayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseExited
        // TODO add your handling code here:
        btnPlay.setContentAreaFilled(false);
    }//GEN-LAST:event_btnPlayMouseExited

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code her
        int row = tblMission.getSelectedRow();
        String missionID = tblMission.getValueAt(row, 0).toString();
        try {
            MissionDTO missionDTO = new MissionDAO().findByPrimaryKey(missionID);
            jTabbedPane1.setEnabledAt(0, false);
            jTabbedPane1.setEnabledAt(1, true);
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane1.setEnabledAt(2, false);
            jTabbedPane1.setEnabledAt(3, false);
            gameplayManager = new GameplayManager(jTabbedPane1,lblHint,accountDTO.getUsername(),classDTO, missionDTO, currentItem, txtMissionQuestion
                    , rdChoice1, rdChoice2, rdChoice3, txtMissionAnswer, pbTemp, pbOverall, pnlPlay);
            cbMissionItem.setSelectedIndex(0);
            gameplayManager.startMission();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error starting mission!");
        }
        
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnSearchMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMissionActionPerformed
        // TODO add your handling code here:
        String attribute = cbSearchMission.getSelectedItem().toString();
        String keyword = txtSearchMission.getText();
        String validate = "";
        
        if(keyword.equals("") && !attribute.equals("All")) validate += "Search keyword can't be blank!";
        if (!validate.equals("")){
            JOptionPane.showMessageDialog(this, validate);
        } else {
            try {
                MissionDAO dao = new MissionDAO();
                List<MissionDTO> list = dao.findByAttribute(attribute, keyword);
                loadMission(list);
                if (list.size()==0) JOptionPane.showMessageDialog(this, "Not found!");
                txtSearchMission.setText("");
                btnPlay.setVisible(false);
                txtWarning.setText(" ");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Search failed!");
            }
        }
    }//GEN-LAST:event_btnSearchMissionActionPerformed

    private void txtSearchMissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchMissionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchMissionActionPerformed

    private void txtAccountUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountUsernameActionPerformed

    private void txtAccountCharNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountCharNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountCharNameActionPerformed

    private void cbAccountRankItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAccountRankItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccountRankItemStateChanged

    private void cbAccountRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAccountRankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccountRankActionPerformed

    private void cbAccountRankPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbAccountRankPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccountRankPropertyChange

    private void cbAccountCharacterClassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAccountCharacterClassItemStateChanged
        // TODO add your handling code here:
        String className = cbAccountCharacterClass.getSelectedItem().toString();
        try {
            ClassDTO classDTO = new ClassDAO().findByPrimaryKey(className);
            String[] des = classDTO.getDescription().split("\\.");
            lblClassDes.setText(des[des.length-1]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading Class Image!");
        }
        imgAccountClass.setIcon(new ImageIcon(getClass().getResource("/popem/img/"+className+"_small.png")));
    }//GEN-LAST:event_cbAccountCharacterClassItemStateChanged

    private void cbAccountCharacterClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbAccountCharacterClassMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbAccountCharacterClassMouseClicked

    private void txtAccountPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccountPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccountPointsActionPerformed

    private void cbAccountRoleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAccountRoleItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccountRoleItemStateChanged

    private void cbAccountRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAccountRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccountRoleActionPerformed

    private void cbAccountRolePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbAccountRolePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAccountRolePropertyChange

    private void tblAccountInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAccountInventoryMouseClicked
        // TODO add your handling code here:
        int row = tblAccountInventory.getSelectedRow();
        lblItemInventoryDes.setText(" ");
        lblDesDropRate.setText(" ");
        String id = tblModelAccountInventory.getValueAt(row, 0).toString().split("-")[0];
        try {
            ItemDAO dao = new ItemDAO();
            ItemDTO dto = dao.findByPrimaryKey(id);
            lblItemName.setText(dto.getName());
            lblItemInventoryDes.setText(dto.getDescription());
            lblDesDropRate.setText("Drop Rate: "+dto.getDropRate()*100+"%");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error retrieving Inventory info!");
        }
    }//GEN-LAST:event_tblAccountInventoryMouseClicked

    private void btnAccountUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountUpdateActionPerformed
        // TODO add your handling code here:
        String validate = "";
        boolean classChanged = false, nameChanged = false;
        String className = cbAccountCharacterClass.getSelectedItem().toString();
        String characterName = txtAccountCharName.getText();
        if(characterName.equals("")) validate += "Character name can't be blank!\n";
        else if (!characterName.matches("\\w{6,12}")) validate += "Character name must be 6-12 characters!\n";
        if(!accountDTO.getCharacterClass().equals(cbAccountCharacterClass.getSelectedItem().toString())){
            accountDTO.setCharacterClass(cbAccountCharacterClass.getSelectedItem().toString());
            classChanged = true;
        }
        if (!accountDTO.getCharacterName().equals(txtAccountCharName.getText())) {
            accountDTO.setCharacterName(txtAccountCharName.getText());
            nameChanged = true;
        }
        
        if (!validate.equals("")) JOptionPane.showMessageDialog(this, validate);
        else {
            if (classChanged || nameChanged) {
                try {
                    AccountDAO dao = new AccountDAO();
                    if (dao.update(accountDTO)) {
                        if (classChanged) {
                            userFrame.getLblCharacterAvatar().setIcon(new ImageIcon(getClass().getResource("/popem/img/"+accountDTO.getCharacterClass()+".png")));
                            userFrame.getLblCharacterAvatarBG().setIcon(new ImageIcon(getClass().getResource("/popem/img/"+accountDTO.getCharacterClass()+"_bg.png")));
                        }
                        JOptionPane.showMessageDialog(this, "Update Successful");
                    }
                    else JOptionPane.showMessageDialog(this, "Update Failed");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Error updating account!");
                }
            }
        }

    }//GEN-LAST:event_btnAccountUpdateActionPerformed

    private void tblCompletedMissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCompletedMissionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCompletedMissionMouseClicked

    private void txtMissionAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMissionAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMissionAnswerActionPerformed

    private void cbMissionItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMissionItemItemStateChanged
        // TODO add your handling code here:
        Object item = cbMissionItem.getSelectedItem();
        String itemID = item == null ? "None" : item.toString().split("-")[0];
        if (itemID.equals("None")){
            currentItem = new ItemDTO();
            lblDes.setText(" ");
            lblRemaining.setText(" ");
        } else {
            ItemDAO itemDAO = new ItemDAO();
            InventoryDAO inventoryDAO = new InventoryDAO();
            ItemDTO dto;
            try {
                dto = itemDAO.getGameplayStats(itemID);
                currentItem = dto;
                dto = itemDAO.findByPrimaryKey(itemID);
                lblDes.setText(dto.getDescription());
                lblRemaining.setText("Remaining: "+inventoryDAO.findByPrimaryKey(accountDTO.getUsername(), itemID).getQuantity());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error retrieving item info!");
            }
        }


    }//GEN-LAST:event_cbMissionItemItemStateChanged

    private void cbMissionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMissionItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMissionItemActionPerformed

    private void btnFinishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseEntered
        // TODO add your handling code here:
        btnFinish.setContentAreaFilled(true);
        btnFinish.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnFinishMouseEntered

    private void btnFinishMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseExited
        // TODO add your handling code here:
        btnPlay.setContentAreaFilled(false);
    }//GEN-LAST:event_btnFinishMouseExited

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        try {
            // TODO add your handling code here:
            gameplayManager.stopMission();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(pnlPlay, "Error stopping Mission!");
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    private void jTabbedPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1PropertyChange

    private void tblLeaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLeaderboardMouseClicked

    }//GEN-LAST:event_tblLeaderboardMouseClicked

    private void jTabbedPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane1ComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane1ComponentShown

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
 
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex()== 2){ // load leaderboard
            try {
                AccountDAO accountDAO = new AccountDAO();
                List<AccountDTO> list = accountDAO.findTopPlayers();
                int i = 1;
                Vector temp;
                tblModelLeaderboard.setRowCount(0);
                for (AccountDTO accountDTO : list){
                    if (i == 20) break;
                    if (accountDTO.getRole().equals("user") && accountDTO.getCharacterName()!=null){
                        temp = accountDTO.toVectorLeaderboard();
                        temp.set(0, i++);
                        tblModelLeaderboard.addRow(temp);
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(pnlRanking, "Error loading leaderboard!");
            }
        } else if (jTabbedPane1.getSelectedIndex() == 3){
            try {
                accountDTO = new AccountDAO().findByPrimaryKey(accountDTO.getUsername());
                CompletedMissionDAO cmDAO = new CompletedMissionDAO();
                cbAccountCharacterClass.setSelectedItem(accountDTO.getCharacterClass());
                txtAccountUsername.setText(accountDTO.getUsername());
                txtAccountCharName.setText(accountDTO.getCharacterName());
                txtAccountPassword.setText(accountDTO.getPassword());
                txtAccountPoints.setText(accountDTO.getPoints()+"");
                cbAccountRank.setSelectedItem(accountDTO.getRank());
                cbAccountRole.setSelectedItem(accountDTO.getRole());
                loadCompletedMission(cmDAO.findByUsername(accountDTO.getUsername()));
                inventoryDTOs = new InventoryDAO().findByUsername(accountDTO.getUsername());
                if (inventoryDTOs!=null) {
                    for (InventoryDTO item : inventoryDTOs){
                        item.setItem(item.getItem()+"-"+new ItemDAO().findByPrimaryKey(item.getItem()).getName());
                    }
                }
                loadInventory(inventoryDTOs);
            } catch (Exception ex) {
                Logger.getLogger(PlayingPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jTabbedPane1.getSelectedIndex() == 0){
            try {
                inventoryDTOs = new InventoryDAO()
                        .findByUsername(accountDTO.getUsername());
                loadCbItem();
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new ChangePasswordFrame(accountDTO.getUsername(),accountDTO.getPassword()).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel User;
    private javax.swing.JButton btnAccountUpdate;
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnSearchMission;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAccountCharacterClass;
    private javax.swing.JComboBox<String> cbAccountRank;
    private javax.swing.JComboBox<String> cbAccountRole;
    private javax.swing.JComboBox<String> cbMissionItem;
    private javax.swing.JComboBox<String> cbSearchMission;
    private javax.swing.JLabel imgAccountClass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblClassDes;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblDesDropRate;
    private javax.swing.JLabel lblHint;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblItemInventoryDes;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JProgressBar pbOverall;
    private javax.swing.JProgressBar pbTemp;
    private javax.swing.JPanel pnlMissionChooser;
    private javax.swing.JPanel pnlPlay;
    private javax.swing.JPanel pnlRanking;
    private javax.swing.JRadioButton rdChoice1;
    private javax.swing.JRadioButton rdChoice2;
    private javax.swing.JRadioButton rdChoice3;
    private javax.swing.JTable tblAccountInventory;
    private javax.swing.JTable tblCompletedMission;
    private javax.swing.JTable tblLeaderboard;
    private javax.swing.JTable tblMission;
    private javax.swing.JTextField txtAccountCharName;
    private javax.swing.JPasswordField txtAccountPassword;
    private javax.swing.JTextField txtAccountPoints;
    private javax.swing.JTextField txtAccountUsername;
    private javax.swing.JTextField txtMissionAnswer;
    private javax.swing.JTextArea txtMissionQuestion;
    private javax.swing.JTextField txtSearchMission;
    private javax.swing.JLabel txtWarning;
    // End of variables declaration//GEN-END:variables
}
