/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.MyLinkedList;
import javax.swing.JOptionPane;
import manager.WordManager;

/**
 *
 * @author tuana
 */
public class AddingEngVieFrame extends javax.swing.JFrame {
    private WordManager wmMain = null;
    /**
     * Creates new form AddingVieEngFrame
     */
    public AddingEngVieFrame() {
        initComponents();
    }
    
    public AddingEngVieFrame(WordManager wmMain) {
        initComponents();
        this.wmMain = wmMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWord = new javax.swing.JTextField();
        txtMeanings = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtWord.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        getContentPane().add(txtWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 560, -1));

        txtMeanings.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        getContentPane().add(txtMeanings, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 560, -1));

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 0, 51));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 120, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Word:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Meanings:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        setSize(new java.awt.Dimension(840, 303));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String word = txtWord.getText();
        String meanings = txtMeanings.getText();
        if(word.equals("") || meanings.equals("")) {
            JOptionPane.showMessageDialog(null, "These fields must be not blank.");
        } else {
            MyLinkedList meaningsList = new MyLinkedList();
        meaningsList.add(meanings);
        wmMain.addEngVie(word, meaningsList);
            word = txtMeanings.getText();
            meanings = txtWord.getText();
            meaningsList.clear();
            meaningsList.add(meanings);
            wmMain.addVieEng(word, meaningsList);
        JOptionPane.showMessageDialog(null, "Insert success");
        this.dispose();
        }        
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingEngVieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingEngVieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingEngVieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingEngVieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingEngVieFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMeanings;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
