/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin.insert;

import anhht.daos.PromotionDAO;
import anhht.dtos.PromotionDTO;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author tuana
 */
public class PromotionInsertFrame extends javax.swing.JFrame {

    private JButton btnDeleteMain = null;
    private JButton btnResetMain = null;
    private JComboBox cbSearchMain = null;
    private JTextField txtCodeMain = null;
    private JButton btnSearchMain = null;

    /**
     * Creates new form PromotionInsertFrame
     */
    public PromotionInsertFrame() {
        initComponents();
    }

    public PromotionInsertFrame(JButton btnDeleteMain, JButton btnResetMain, JComboBox cbSearchMain, JTextField txtCodeMain, JButton btnSearchMain) {
        initComponents();
        this.btnDeleteMain = btnDeleteMain;
        this.btnResetMain = btnResetMain;
        this.cbSearchMain = cbSearchMain;
        this.txtCodeMain = txtCodeMain;
        this.btnSearchMain = btnSearchMain;
        setDefaultStartTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPromotionInfo = new javax.swing.JLabel();
        pnlCarCatInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        msgDiscount = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spStartTime = new javax.swing.JSpinner();
        spEndTime = new javax.swing.JSpinner();
        msgTime = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        msgCode = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPromotionInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblPromotionInfo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblPromotionInfo.setForeground(new java.awt.Color(255, 0, 0));
        lblPromotionInfo.setText("Promotion Info");
        getContentPane().add(lblPromotionInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        pnlCarCatInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlCarCatInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Code:");
        pnlCarCatInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 27, -1, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Discount:");
        pnlCarCatInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 30));

        txtDiscount.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtDiscount.setForeground(new java.awt.Color(51, 51, 255));
        pnlCarCatInfo.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("%");
        pnlCarCatInfo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 30));

        msgDiscount.setForeground(new java.awt.Color(255, 0, 0));
        pnlCarCatInfo.add(msgDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, 20));

        txtCode.setEditable(false);
        txtCode.setBackground(new java.awt.Color(255, 255, 255));
        txtCode.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtCode.setForeground(new java.awt.Color(51, 51, 255));
        pnlCarCatInfo.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Start Time:");
        pnlCarCatInfo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("End Time:");
        pnlCarCatInfo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        spStartTime.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spStartTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1552742958015L), null, null, java.util.Calendar.HOUR));
        spStartTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCarCatInfo.add(spStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        spEndTime.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spEndTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1552742958015L), null, null, java.util.Calendar.HOUR));
        spEndTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCarCatInfo.add(spEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        msgTime.setForeground(new java.awt.Color(255, 51, 51));
        pnlCarCatInfo.add(msgTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 230, 20));

        btnGenerate.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerate.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnGenerate.setForeground(new java.awt.Color(255, 0, 0));
        btnGenerate.setText("Generate");
        btnGenerate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        pnlCarCatInfo.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 130, -1));

        msgCode.setForeground(new java.awt.Color(255, 51, 51));
        pnlCarCatInfo.add(msgCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, 20));

        getContentPane().add(pnlCarCatInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 580, 410));

        btnReset.setBackground(new java.awt.Color(255, 255, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/5c8dd48504f17.png"))); // NOI18N
        btnReset.setToolTipText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 50, 50));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/add-1-icon.png"))); // NOI18N
        btnInsert.setToolTipText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 50, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 2660, 1220));

        setSize(new java.awt.Dimension(712, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtCode.setText("");
        msgCode.setText("");
        txtDiscount.setText("");
        msgDiscount.setText("");
        msgTime.setText("");
        setDefaultStartTime();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        String code = txtCode.getText();
        float discount = 0;
        Timestamp startTime, endTime;
        try {
            int temp = Integer.parseInt(txtDiscount.getText());
            discount = (float) Math.round(temp) / 100;
        } catch (NumberFormatException e) {
        }
        Date StartTime = (Date) spStartTime.getValue();
        Date EndTime = (Date) spEndTime.getValue();
        startTime = new Timestamp(StartTime.getTime());
        endTime = new Timestamp(EndTime.getTime());
        PromotionDAO pDAO = new PromotionDAO();
        if (validate(code, discount, startTime, endTime)) {
            if (pDAO.insert(new PromotionDTO(code, discount, startTime, endTime))) {
                JOptionPane.showMessageDialog(null, "Insert success");
                btnDeleteMain.setEnabled(false);
                cbSearchMain.setSelectedIndex(0);
                btnSearchMain.doClick();
                btnResetMain.doClick();
                txtCodeMain.setText("");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Insert failed");
            }

        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
        String AlphanumbericString = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        // create StringBuffer size of AlphaNumericString
        StringBuilder sb = new StringBuilder(10);
        PromotionDAO pDAO = new PromotionDAO();
        String result = null;
        do {
            for (int i = 0; i < 10; i++) {
                // generate a random number between
                // 0 to NumericString variable length
                int index = (int) (AlphanumbericString.length() * Math.random());
                // add Character one by one in end of sb
                sb.append(AlphanumbericString.charAt(index));
            }
            result = sb.toString();
        } while (pDAO.findExisting(result));
        txtCode.setText(result);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void setDefaultStartTime() {
        SpinnerDateModel sdm1 = (SpinnerDateModel) spStartTime.getModel();
        SpinnerDateModel sdm2 = (SpinnerDateModel) spEndTime.getModel();
        Date minDate = new Date(Calendar.getInstance().getTimeInMillis());
        Date currDate = new Date(Calendar.getInstance().getTimeInMillis() + 300000);
        sdm1.setStart(minDate);
        sdm1.setValue(currDate);
        sdm2.setStart(minDate);
        sdm2.setValue(currDate);
        ((JSpinner.DefaultEditor) spStartTime.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) spEndTime.getEditor()).getTextField().setEditable(false);
    }

    private boolean validate(String code, float discount, Timestamp startTime, Timestamp endTime) {
        boolean check = true;
        if (code.equals("")) {
            check = false;
            msgCode.setText("Press Generate button to get an ID");
        } else {
            msgCode.setText("");
        }
        if (discount < 1.0f && discount > 0) {
            msgDiscount.setText("");
        } else {
            msgDiscount.setText("Discount is invalid.");
            check = false;
        }
        if (startTime.getTime() >= endTime.getTime()) {
            msgTime.setText("EndTime must be further than StartTime.");
            check = false;
        } else {
            msgTime.setText("");
        }
        return check;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromotionInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromotionInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromotionInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromotionInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromotionInsertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPromotionInfo;
    private javax.swing.JLabel msgCode;
    private javax.swing.JLabel msgDiscount;
    private javax.swing.JLabel msgTime;
    private javax.swing.JPanel pnlCarCatInfo;
    private javax.swing.JSpinner spEndTime;
    private javax.swing.JSpinner spStartTime;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDiscount;
    // End of variables declaration//GEN-END:variables
}
