/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin.insert;

import anhht.daos.CarCategoryDAO;
import anhht.daos.CarDAO;
import anhht.daos.EmpDAO;
import anhht.daos.TravelPriceDAO;
import anhht.daos.TravelTransactionDAO;
import anhht.dtos.CarCategoryDTO;
import anhht.dtos.CarDTO;
import anhht.dtos.EmployeeDTO;
import anhht.dtos.TravelPriceDTO;
import anhht.dtos.TravelTransactionDTO;
import java.awt.CardLayout;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import myutil.MyUtil;

/**
 *
 * @author tuana
 */
public class TransInsertFrame extends javax.swing.JFrame {

    /**
     * Creates new form TransInsertFrame
     */
    private String cusID;
    private JButton btnSearchMain = null;
    private JButton btnDeleteMain = null;
    private DefaultTableModel tblModelTravelPrice = null;
    private DefaultTableModel tblModelCar = null;
    private DefaultTableModel tblModelEmployee = null;

    public TransInsertFrame() {
        initComponents();
    }

    public TransInsertFrame(String cusID, JButton btnSearchMain, JButton btnDeleteMain, DefaultTableModel tblModelTransactionMain) {
        initComponents();
        this.cusID = cusID;
        this.btnSearchMain = btnSearchMain;
        this.btnDeleteMain = btnDeleteMain;
        loadCarCategory();
        tblModelTravelPrice = (DefaultTableModel) tblViewTravelPrice.getModel();
        tblModelCar = (DefaultTableModel) tblViewCar.getModel();
        tblModelEmployee = (DefaultTableModel) tblViewEmployee.getModel();
        btnSearchTravel.doClick();
    }

    private void showTravelPrice(List<TravelPriceDTO> list) {
        tblModelTravelPrice.setRowCount(0);
        for (TravelPriceDTO travelPriceDTO : list) {
            tblModelTravelPrice.addRow(travelPriceDTO.toVector());
        }
    }

    private void showCar(List<CarDTO> list) {
        tblModelCar.setRowCount(0);
        for (CarDTO carDTO : list) {
            tblModelCar.addRow(carDTO.toVector2());
        }
    }

    private void showEmployee(List<EmployeeDTO> list) {
        tblModelEmployee.setRowCount(0);
        for (EmployeeDTO employeeDTO : list) {
            tblModelEmployee.addRow(employeeDTO.toVector());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBookCar = new javax.swing.JPanel();
        pnlChooseTravel = new javax.swing.JPanel();
        txtSearchTravel = new javax.swing.JTextField();
        btnSearchTravel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewTravelPrice = new javax.swing.JTable();
        btnResetTravel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbSeats = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        btnNextCar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlChooseCar = new javax.swing.JPanel();
        txtSearchCar = new javax.swing.JTextField();
        btnSearchCar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblViewCar = new javax.swing.JTable();
        lblStartTime = new javax.swing.JLabel();
        lblDuration = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        btnBackTravel = new javax.swing.JButton();
        btnResetCar = new javax.swing.JButton();
        lblSeats = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spDuration = new javax.swing.JSpinner();
        lblPrice = new javax.swing.JLabel();
        btnNextEmp = new javax.swing.JButton();
        spStartTime = new javax.swing.JSpinner();
        lblCarName = new javax.swing.JLabel();
        btnPromotion = new javax.swing.JButton();
        lblDiscount = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlChooseEmp = new javax.swing.JPanel();
        txtSearchEmp = new javax.swing.JTextField();
        btnSearchEmp = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnBackCar = new javax.swing.JButton();
        lblEmp = new javax.swing.JLabel();
        btnResetEmp = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblViewEmployee = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBookCar.setLayout(new java.awt.CardLayout());

        pnlChooseTravel.setEnabled(false);
        pnlChooseTravel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchTravel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSearchTravel.setForeground(new java.awt.Color(255, 51, 0));
        pnlChooseTravel.add(txtSearchTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 233, 50));

        btnSearchTravel.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchTravel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearchTravel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/searching-2339723_1920.png"))); // NOI18N
        btnSearchTravel.setActionCommand("btnSearch");
        btnSearchTravel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTravelActionPerformed(evt);
            }
        });
        pnlChooseTravel.add(btnSearchTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 50, -1));

        tblViewTravelPrice.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tblViewTravelPrice.setForeground(new java.awt.Color(51, 51, 255));
        tblViewTravelPrice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Destination", "Limit Time", "Estimated Distance", "Number Of Seats", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewTravelPrice.setRowHeight(24);
        tblViewTravelPrice.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblViewTravelPrice.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblViewTravelPrice);

        pnlChooseTravel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 131, 911, 527));

        btnResetTravel.setBackground(new java.awt.Color(255, 255, 255));
        btnResetTravel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnResetTravel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/5c8dd48504f17.png"))); // NOI18N
        btnResetTravel.setToolTipText("Reset");
        btnResetTravel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetTravelActionPerformed(evt);
            }
        });
        pnlChooseTravel.add(btnResetTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 50, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Travel Price");
        pnlChooseTravel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, -1, 70));

        cbSeats.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        cbSeats.setForeground(new java.awt.Color(255, 51, 0));
        cbSeats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlChooseTravel.add(cbSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 70, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Seats:");
        pnlChooseTravel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 50));

        lblDestination.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblDestination.setForeground(new java.awt.Color(255, 0, 0));
        lblDestination.setText("Destination:");
        pnlChooseTravel.add(lblDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 50));

        btnNextCar.setBackground(new java.awt.Color(255, 255, 255));
        btnNextCar.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnNextCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/2f85ac179c.png"))); // NOI18N
        btnNextCar.setToolTipText("Next");
        btnNextCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNextCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextCarActionPerformed(evt);
            }
        });
        pnlChooseTravel.add(btnNextCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 680, 50, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        pnlChooseTravel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 2660, 1220));

        pnlBookCar.add(pnlChooseTravel, "card1");

        pnlChooseCar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchCar.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSearchCar.setForeground(new java.awt.Color(255, 0, 0));
        txtSearchCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchCarActionPerformed(evt);
            }
        });
        pnlChooseCar.add(txtSearchCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 430, 50));

        btnSearchCar.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchCar.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearchCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/searching-2339723_1920.png"))); // NOI18N
        btnSearchCar.setActionCommand("btnSearch");
        btnSearchCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarActionPerformed(evt);
            }
        });
        pnlChooseCar.add(btnSearchCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 50, -1));

        tblViewCar.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tblViewCar.setForeground(new java.awt.Color(51, 51, 255));
        tblViewCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car Seiral", "Car Name", "Number Of Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewCar.setRowHeight(24);
        tblViewCar.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblViewCar.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblViewCar);

        pnlChooseCar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 131, 911, 453));

        lblStartTime.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblStartTime.setForeground(new java.awt.Color(51, 51, 255));
        lblStartTime.setText("Start Time:");
        pnlChooseCar.add(lblStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, 30));

        lblDuration.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(51, 51, 255));
        lblDuration.setText("Duration:");
        pnlChooseCar.add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(51, 51, 255));
        pnlChooseCar.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 160, 30));

        btnBackTravel.setBackground(new java.awt.Color(255, 255, 255));
        btnBackTravel.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnBackTravel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/2f85ac179back.png"))); // NOI18N
        btnBackTravel.setToolTipText("Back");
        btnBackTravel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTravelActionPerformed(evt);
            }
        });
        pnlChooseCar.add(btnBackTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 610, 50, -1));

        btnResetCar.setBackground(new java.awt.Color(255, 255, 255));
        btnResetCar.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnResetCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/5c8dd48504f17.png"))); // NOI18N
        btnResetCar.setToolTipText("Reset");
        btnResetCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCarActionPerformed(evt);
            }
        });
        pnlChooseCar.add(btnResetCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 660, 50, -1));

        lblSeats.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSeats.setForeground(new java.awt.Color(255, 0, 0));
        lblSeats.setText("Seats: ");
        pnlChooseCar.add(lblSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 59, -1, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Hour(s)");
        pnlChooseCar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, -1, 30));

        spDuration.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spDuration.setModel(new javax.swing.SpinnerNumberModel());
        spDuration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spDuration.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spDurationStateChanged(evt);
            }
        });
        pnlChooseCar.add(spDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 680, 80, -1));

        lblPrice.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(51, 51, 255));
        lblPrice.setText("Price:");
        pnlChooseCar.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, -1, 40));

        btnNextEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnNextEmp.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnNextEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/2f85ac179c.png"))); // NOI18N
        btnNextEmp.setToolTipText("Next");
        btnNextEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNextEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextEmpActionPerformed(evt);
            }
        });
        pnlChooseCar.add(btnNextEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 710, 50, -1));

        spStartTime.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spStartTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR));
        spStartTime.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spStartTime.setInheritsPopupMenu(true);
        spStartTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spStartTimeStateChanged(evt);
            }
        });
        pnlChooseCar.add(spStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, -1, -1));

        lblCarName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblCarName.setForeground(new java.awt.Color(255, 0, 51));
        lblCarName.setText("Car Name:");
        pnlChooseCar.add(lblCarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 50));

        btnPromotion.setBackground(new java.awt.Color(255, 255, 255));
        btnPromotion.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnPromotion.setForeground(new java.awt.Color(255, 0, 0));
        btnPromotion.setText("Promotion");
        btnPromotion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromotionActionPerformed(evt);
            }
        });
        pnlChooseCar.add(btnPromotion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 610, -1, 50));

        lblDiscount.setForeground(new java.awt.Color(255, 51, 51));
        pnlChooseCar.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, 280, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        pnlChooseCar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 2660, 1220));

        pnlBookCar.add(pnlChooseCar, "card2");

        pnlChooseEmp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchEmp.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSearchEmp.setForeground(new java.awt.Color(255, 51, 0));
        pnlChooseEmp.add(txtSearchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 430, 50));

        btnSearchEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchEmp.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearchEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/searching-2339723_1920.png"))); // NOI18N
        btnSearchEmp.setActionCommand("btnSearch");
        btnSearchEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmpActionPerformed(evt);
            }
        });
        pnlChooseEmp.add(btnSearchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 50, -1));

        btnBook.setBackground(new java.awt.Color(255, 255, 255));
        btnBook.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/kisspng-computer-icons-purchase-order-order-fulfillment-pu-order-icon-5b234a157ef483.72670950152903938152.png"))); // NOI18N
        btnBook.setToolTipText("Book");
        btnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        pnlChooseEmp.add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 710, 50, 50));

        btnBackCar.setBackground(new java.awt.Color(255, 255, 255));
        btnBackCar.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnBackCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/2f85ac179back.png"))); // NOI18N
        btnBackCar.setToolTipText("Back");
        btnBackCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCarActionPerformed(evt);
            }
        });
        pnlChooseEmp.add(btnBackCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 610, 50, -1));

        lblEmp.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblEmp.setForeground(new java.awt.Color(255, 0, 0));
        lblEmp.setText("Emp Name:");
        pnlChooseEmp.add(lblEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 50));

        btnResetEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnResetEmp.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnResetEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/5c8dd48504f17.png"))); // NOI18N
        btnResetEmp.setToolTipText("Reset");
        btnResetEmp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetEmpActionPerformed(evt);
            }
        });
        pnlChooseEmp.add(btnResetEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 660, 50, -1));

        tblViewEmployee.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        tblViewEmployee.setForeground(new java.awt.Color(51, 51, 255));
        tblViewEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "Name", "Sex", "Age", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewEmployee.setRowHeight(24);
        tblViewEmployee.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(tblViewEmployee);

        pnlChooseEmp.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 910, 470));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anhht/imgs/y1ostvqnr4711.png"))); // NOI18N
        pnlChooseEmp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -70, 2660, 1220));

        pnlBookCar.add(pnlChooseEmp, "card3");

        getContentPane().add(pnlBookCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(975, 846));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTravelActionPerformed
        // TODO add your handling code here:
        TravelPriceDAO tpDAO = new TravelPriceDAO();
        List<TravelPriceDTO> result = null;
        String seatString = (String) cbSeats.getSelectedItem();
        if (seatString.equals("All")) {
            if (txtSearchTravel.getText().equals("")) {
                result = tpDAO.findAll();
            } else {
                result = tpDAO.findByDestination(txtSearchTravel.getText());
            }
        } else {
            try {
                int seats = Integer.parseInt(seatString);
                if (txtSearchTravel.getText().equals("")) {
                    result = tpDAO.findBySeats(seats);
                } else {
                    result = tpDAO.findByDestinationAndSeats(txtSearchTravel.getText(), seats);
                }
            } catch (NumberFormatException e) {
            }
        }
        if (result.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Not found any travel");
            btnResetTravel.doClick();
        } else {
            showTravelPrice(result);
        }
    }//GEN-LAST:event_btnSearchTravelActionPerformed

    private void btnResetTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetTravelActionPerformed
        // TODO add your handling code here:
        cbSeats.setSelectedIndex(0);
        txtSearchTravel.setText("");
        tblModelTravelPrice.setRowCount(0);
    }//GEN-LAST:event_btnResetTravelActionPerformed

    private void btnSearchCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarActionPerformed
        // TODO add your handling code here:
        try {
            CarDAO carDAO = new CarDAO();
            List<CarDTO> result = null;
            Timestamp startTime, endTime;
            int seats = 0, duration;
            try {
                seats = Integer.parseInt(lblSeats.getText().substring(7));
            } catch (Exception e) {
            }
            Date date = (Date) spStartTime.getValue();
            startTime = new Timestamp(date.getTime());
            duration = (Integer) spDuration.getValue();
            endTime = new Timestamp(startTime.getTime() + duration * 3600000);
            if (seats != 0) {
                if (txtSearchCar.getText().equals("")) {
                    result = carDAO.findAvailableBySeats(seats, startTime, endTime);
                } else {
                    result = carDAO.findAvailableByCarNameAndSeats(txtSearchCar.getText(), seats, startTime, endTime);
                }
            }
            if (result.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Not Found car!");
                btnResetCar.doClick();
            } else {
                showCar(result);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchCarActionPerformed

    private void btnBackTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTravelActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) pnlBookCar.getLayout();
        cl.show(pnlBookCar, "card1");
    }//GEN-LAST:event_btnBackTravelActionPerformed

    private void btnResetCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCarActionPerformed
        // TODO add your handling code here:
        txtSearchCar.setText("");
        tblModelCar.setRowCount(0);
        SpinnerNumberModel snm = (SpinnerNumberModel) spDuration.getModel();
        snm.setValue(snm.getMinimum());
        setDefaultStartTime();
    }//GEN-LAST:event_btnResetCarActionPerformed

    private void spDurationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spDurationStateChanged
        // TODO add your handling code here:
        btnSearchCar.doClick();
        changePrice();
    }//GEN-LAST:event_spDurationStateChanged

    private void btnNextCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextCarActionPerformed
        // TODO add your handling code here:
        try {
            int row = tblViewTravelPrice.getSelectedRow();
            String travelID = (String) tblModelTravelPrice.getValueAt(row, 0);
            TravelPriceDAO tpDAO = new TravelPriceDAO();
            TravelPriceDTO tpDTO = tpDAO.findByPrimaryKey(travelID);
            if (tpDTO != null) {
                lblSeats.setText("Seats: " + tpDTO.getNumberOfSeats());
                setDefaultDuration(tpDTO.getLimitTime());
                btnResetCar.doClick();
                btnSearchCar.doClick();
                if (lblDiscount.getText().equals("")) {
                    loadDiscount();
                    if (lblDiscount.getText().equals("")) {
                        btnPromotion.setEnabled(true);
                    } else {
                        btnPromotion.setEnabled(false);
                    }
                }
                CardLayout cl = (CardLayout) pnlBookCar.getLayout();
                cl.show(pnlBookCar, "card2");
            } else {
                JOptionPane.showMessageDialog(null, "Not found your account", "System warning", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select travel destination");
        }
    }//GEN-LAST:event_btnNextCarActionPerformed

    private void btnNextEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextEmpActionPerformed
        // TODO add your handling code here:
        int row = tblViewCar.getSelectedRow();
        if (row != -1) {
            btnResetEmp.doClick();
            btnSearchEmp.doClick();
            CardLayout cl = (CardLayout) pnlBookCar.getLayout();
            cl.show(pnlBookCar, "card3");
        } else {
            JOptionPane.showMessageDialog(null, "Please choose car");
        }
    }//GEN-LAST:event_btnNextEmpActionPerformed

    private void spStartTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spStartTimeStateChanged
        // TODO add your handling code here:
        btnSearchCar.doClick();
    }//GEN-LAST:event_spStartTimeStateChanged

    private void btnSearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmpActionPerformed
        // TODO add your handling code here:
        EmpDAO empDAO = new EmpDAO();
        List<EmployeeDTO> result = null;
        Timestamp startTime, endTime;
        int seats = 0, duration;
        try {
            seats = Integer.parseInt(lblSeats.getText().substring(7));
        } catch (Exception e) {
        }
        Date date = (Date) spStartTime.getValue();
        startTime = new Timestamp(date.getTime());
        duration = (Integer) spDuration.getValue();
        endTime = new Timestamp(startTime.getTime() + duration * 3600000);
        if (seats != 0) {
            if (txtSearchEmp.getText().equals("")) {
                result = empDAO.findAvailableBySeats(seats, startTime, endTime);
            } else {
                result = empDAO.findAvailableByEmpNameAndSeats(txtSearchEmp.getText(), seats, startTime, endTime);
            }
        }
        if (result.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Not Found employee!");
            btnResetEmp.doClick();
        } else {
            showEmployee(result);
        }
    }//GEN-LAST:event_btnSearchEmpActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        boolean check = true;
        TravelTransactionDAO ttDAO = new TravelTransactionDAO();
        String transID, travelID = null, carSerial = null, empID = null;
        Timestamp startTime;
        int duration, price = 0;
        //Get ID transaction        
        transID = Long.toString(new Date().getTime());
        //Get travelID
        try {
            int rowTblTravelPrice = tblViewTravelPrice.getSelectedRow();
            if (rowTblTravelPrice == -1) {
                check = false;
            }
            travelID = (String) tblModelTravelPrice.getValueAt(rowTblTravelPrice, 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select travel destination!");
        }
        //Get Car serial
        try {
            int rowTblCar = tblViewCar.getSelectedRow();
            if (rowTblCar == -1) {
                check = false;
            }
            carSerial = (String) tblModelCar.getValueAt(rowTblCar, 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select car!");
        }
        //Get empID
        try {
            int rowTblEmp = tblViewEmployee.getSelectedRow();
            if (rowTblEmp == -1) {
                check = false;
            }
            empID = (String) tblModelEmployee.getValueAt(rowTblEmp, 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please select employee!");
        }
        //Get start time
        Date date = (Date) spStartTime.getValue();
        startTime = new Timestamp(date.getTime());
        //Get duration
        duration = (Integer) spDuration.getValue();
        //Get price
        try {
            if (txtPrice.getText().equals("")) {
                check = false;
            }
            price = Integer.parseInt(txtPrice.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please count the price!");
        }
        if (check) {
            if (ttDAO.insert(new TravelTransactionDTO(transID, travelID, cusID, empID, carSerial, price, duration, startTime))) {
                JOptionPane.showMessageDialog(null, "Book car success");
                btnDeleteMain.setEnabled(false);
                btnSearchMain.doClick();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Book car failed!");
            }
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnBackCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCarActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) pnlBookCar.getLayout();
        cl.show(pnlBookCar, "card2");
    }//GEN-LAST:event_btnBackCarActionPerformed

    private void btnResetEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetEmpActionPerformed
        // TODO add your handling code here:
        txtSearchEmp.setText("");
        tblModelEmployee.setRowCount(0);
    }//GEN-LAST:event_btnResetEmpActionPerformed

    private void btnPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromotionActionPerformed
        // TODO add your handling code here:
        new PromotionActivationFrame(lblDiscount, tblViewTravelPrice, spDuration, txtPrice).setVisible(true);
    }//GEN-LAST:event_btnPromotionActionPerformed

    private void txtSearchCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchCarActionPerformed

    private void loadCarCategory() {
        CarCategoryDAO carCateDAO = new CarCategoryDAO();
        List<CarCategoryDTO> result = carCateDAO.findAll();
        cbSeats.addItem("All");
        for (CarCategoryDTO carCategoryDTO : result) {
            cbSeats.addItem(Integer.toString(carCategoryDTO.getNumberOfSeats()));
        }
    }

    private void setDefaultDuration(int min) {
        SpinnerNumberModel snm = (SpinnerNumberModel) spDuration.getModel();
        snm.setMinimum(min);
        snm.setMaximum(120);
        snm.setValue(min);
        snm.setStepSize(1);
        ((JSpinner.DefaultEditor) spDuration.getEditor()).getTextField().setEditable(false);
    }

    private void setDefaultStartTime() {
        SpinnerDateModel sdm = (SpinnerDateModel) spStartTime.getModel();
        Date minDate = new Date(Calendar.getInstance().getTimeInMillis());
        Date currDate = new Date(Calendar.getInstance().getTimeInMillis() + 300000);
        sdm.setStart(minDate);
        sdm.setValue(currDate);
        ((JSpinner.DefaultEditor) spStartTime.getEditor()).getTextField().setEditable(false);
    }

    private void loadDiscount() {
        try {
            int row = tblViewTravelPrice.getSelectedRow();
            String travelID = (String) tblModelTravelPrice.getValueAt(row, 0);
            TravelPriceDAO tpDAO = new TravelPriceDAO();
            TravelPriceDTO tpDTO = tpDAO.findByPrimaryKey(travelID);
            CarCategoryDAO ccDAO = new CarCategoryDAO();
            CarCategoryDTO ccDTO = ccDAO.findByPrimaryKey(tpDTO.getNumberOfSeats());
            TravelTransactionDAO ttDAO = new TravelTransactionDAO();
            List<TravelTransactionDTO> result = ttDAO.findByCusID(cusID);
            if (result.size() % 4 == 0 && !result.isEmpty()) {
                lblDiscount.setText("Discount " + Integer.toString(Math.round(ccDTO.getDiscount() * 100)) + "%");
            } else {
                lblDiscount.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void changePrice() {
        try {
            int result;
            int row = tblViewTravelPrice.getSelectedRow();
            int duration = (Integer) spDuration.getValue();
            float discount = 0;
            if (!lblDiscount.getText().equals("")) {
                try {
                    discount = Float.parseFloat(lblDiscount.getText().substring(10, lblDiscount.getText().length() - 1)) / 100;
                } catch (NumberFormatException e) {
                }
            }
            String travelID = (String) tblModelTravelPrice.getValueAt(row, 0);
            TravelPriceDAO tpDAO = new TravelPriceDAO();
            TravelPriceDTO tpDTO = tpDAO.findByPrimaryKey(travelID);
            CarCategoryDAO ccDAO = new CarCategoryDAO();
            CarCategoryDTO ccDTO = ccDAO.findByPrimaryKey(tpDTO.getNumberOfSeats());
            result = MyUtil.countPrice(tpDTO.getPrice(), tpDTO.getLimitTime(), duration, ccDTO.getSurchargeHr(), discount);
            txtPrice.setText(Integer.toString(result));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransInsertFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransInsertFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransInsertFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransInsertFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransInsertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackCar;
    private javax.swing.JButton btnBackTravel;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnNextCar;
    private javax.swing.JButton btnNextEmp;
    private javax.swing.JButton btnPromotion;
    private javax.swing.JButton btnResetCar;
    private javax.swing.JButton btnResetEmp;
    private javax.swing.JButton btnResetTravel;
    private javax.swing.JButton btnSearchCar;
    private javax.swing.JButton btnSearchEmp;
    private javax.swing.JButton btnSearchTravel;
    private javax.swing.JComboBox<String> cbSeats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JPanel pnlBookCar;
    private javax.swing.JPanel pnlChooseCar;
    private javax.swing.JPanel pnlChooseEmp;
    private javax.swing.JPanel pnlChooseTravel;
    private javax.swing.JSpinner spDuration;
    private javax.swing.JSpinner spStartTime;
    private javax.swing.JTable tblViewCar;
    private javax.swing.JTable tblViewEmployee;
    private javax.swing.JTable tblViewTravelPrice;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JTextField txtSearchCar;
    private javax.swing.JTextField txtSearchEmp;
    private javax.swing.JTextField txtSearchTravel;
    // End of variables declaration//GEN-END:variables
}
