/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin.insert;

import anht.daos.CustomerDAO;
import anht.dtos.CustomerDTO;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author tuana
 */
public class AccInsertFrame extends javax.swing.JFrame {

    private JButton btnSearchMain = null;
    private JButton btnDeleteMain = null;
    private JButton btnResetMain = null;
    private JTextField txtSearchMain = null;
    private JTextField txtUsernameMain = null;

    /**
     * Creates new form AccInsertFrame
     */
    public AccInsertFrame() {
        initComponents();
    }

    public AccInsertFrame(JButton btnSearchMain, JButton btnDeleteMain, JButton btnResetMain, JTextField txtSearchMain, JTextField txtUsernameMain) {
        initComponents();
        this.btnSearchMain = btnSearchMain;
        this.btnDeleteMain = btnDeleteMain;
        this.btnResetMain = btnResetMain;
        this.txtSearchMain = txtSearchMain;
        this.txtUsernameMain = txtUsernameMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupSex = new javax.swing.ButtonGroup();
        pnlUserInfo = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPass = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        lblSex = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        rdMale = new javax.swing.JRadioButton();
        rdFemale = new javax.swing.JRadioButton();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        msgUsername = new javax.swing.JLabel();
        msgPass = new javax.swing.JLabel();
        msgName = new javax.swing.JLabel();
        msgAge = new javax.swing.JLabel();
        msgPhone = new javax.swing.JLabel();
        msgPass2 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblCarInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUserInfo.setBackground(new java.awt.Color(204, 255, 153));
        pnlUserInfo.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.setPreferredSize(new java.awt.Dimension(51, 20));
        pnlUserInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblUsername.setText("Username:");
        pnlUserInfo.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 31, -1, 30));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 255, 51));
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 30, 390, -1));

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPass.setText("Password:");
        pnlUserInfo.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 106, 28));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPass.setForeground(new java.awt.Color(51, 255, 51));
        txtPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 107, 390, -1));

        lblSex.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSex.setText("Sex:");
        pnlUserInfo.add(lblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 270, -1, 37));

        txtAge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtAge.setForeground(new java.awt.Color(51, 255, 51));
        txtAge.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 363, 390, -1));

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblAge.setText("Age:");
        pnlUserInfo.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 365, -1, 28));

        rdMale.setBackground(new java.awt.Color(204, 255, 153));
        groupSex.add(rdMale);
        rdMale.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdMale.setSelected(true);
        rdMale.setText("Male");
        pnlUserInfo.add(rdMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 271, -1, -1));

        rdFemale.setBackground(new java.awt.Color(204, 255, 153));
        groupSex.add(rdFemale);
        rdFemale.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        rdFemale.setText("Female");
        pnlUserInfo.add(rdFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblPhone.setText("Phone Number:");
        pnlUserInfo.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 451, -1, 28));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(51, 255, 51));
        txtPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 449, 390, -1));

        lblName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblName.setText("Fullname:");
        pnlUserInfo.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 186, -1, 28));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 255, 51));
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlUserInfo.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 184, 390, -1));

        msgUsername.setForeground(new java.awt.Color(255, 51, 51));
        msgUsername.setPreferredSize(new java.awt.Dimension(51, 20));
        pnlUserInfo.add(msgUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 72, 386, 17));

        msgPass.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 149, 386, 17));

        msgName.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 226, 183, 17));

        msgAge.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 405, 183, 17));

        msgPhone.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 491, 183, 14));

        msgPass2.setForeground(new java.awt.Color(255, 51, 51));
        pnlUserInfo.add(msgPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 167, 386, 17));

        getContentPane().add(pnlUserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 660, 530));

        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, 120, -1));

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 640, 120, -1));

        lblCarInfo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarInfo.setText("Account Info");
        getContentPane().add(lblCarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        setSize(new java.awt.Dimension(906, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String pass = new String(txtPass.getPassword());
        String fullname = txtName.getText();
        String phone = txtPhone.getText();
        boolean sex = rdMale.isSelected();
        int age = 0;
        try {
            age = Integer.parseInt(txtAge.getText());
        } catch (NumberFormatException e) {
        }
        CustomerDAO accDAO = new CustomerDAO();
        if (validate(username, pass, fullname, phone, age)) {
            if (accDAO.insert(new CustomerDTO(username, pass, fullname, phone, sex, age))) {
                JOptionPane.showMessageDialog(null, "Insert success");
                btnDeleteMain.setEnabled(false);
                txtSearchMain.setText("");
                btnSearchMain.doClick();
                btnResetMain.doClick();
                txtUsernameMain.setText("");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Insert failed");
            }

        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtUsername.setText("");
        txtPass.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtAge.setText("");
        rdMale.setSelected(true);
        msgUsername.setText("");
        msgPass.setText("");
        msgPass2.setText("");
        msgName.setText("");
        msgPhone.setText("");
        msgAge.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private boolean validate(String username, String pass, String fullname, String phone, int age) {
        boolean check = true;
        String usernamePattern = "[\\w]{7,}";
        String passPattern = "(?=.*\\d)(?=.*[a-zA-Z])[\\w]{8,}";
        String phonePattern = "\\d{10}";
        CustomerDAO accDAO = new CustomerDAO();
        if (!username.matches(usernamePattern)) {
            msgUsername.setText("Username must be 7 or more alphanumberic characters.\n");
            check = false;
        } else if (accDAO.findExisting(username)) {
            msgUsername.setText("Username is existed.");
            check = false;
        } else {
            msgUsername.setText("");
        }
        if (!pass.matches(passPattern)) {
            msgPass.setText("Password must be 8 or more alphanumberic characters");
            msgPass2.setText("including at least 1 letter and 1 numberic letter.");
            check = false;
        } else {
            msgPass.setText("");
            msgPass2.setText("");
        }
        if (fullname.equals("")) {
            msgName.setText("Full name is not empty.");
            check = false;
        } else {
            msgName.setText("");
        }
        if (!phone.matches(phonePattern)) {
            msgPhone.setText("Phone is the sequence of 10 digits.");
            check = false;
        } else {
            msgPhone.setText("");
        }

        if (age < 1) {
            msgAge.setText("Age is a positive number");
            check = false;
        } else {
            msgAge.setText("");
        }
        return check;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccInsertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup groupSex;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCarInfo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel msgAge;
    private javax.swing.JLabel msgName;
    private javax.swing.JLabel msgPass;
    private javax.swing.JLabel msgPass2;
    private javax.swing.JLabel msgPhone;
    private javax.swing.JLabel msgUsername;
    private javax.swing.JPanel pnlUserInfo;
    private javax.swing.JRadioButton rdFemale;
    private javax.swing.JRadioButton rdMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
