/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anhht.gui.admin.insert;

import anht.daos.CarCategoryDAO;
import anht.dtos.CarCategoryDTO;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author tuana
 */
public class CarCatInsertFrame extends javax.swing.JFrame {
    private JButton btnShowAllMain = null;
    private JButton btnDeleteMain = null;
    private JButton btnResetMain = null;
    private JSpinner spSearchMain = null;
    private JSpinner spSeatsMain = null;
    /**
     * Creates new form CarCatInsertFrame
     */
    public CarCatInsertFrame() {
        initComponents();
    }

    public CarCatInsertFrame(JButton btnShowAllMain, JButton btnDeleteMain, JButton btnResetMain, JSpinner spSearchMain, JSpinner spSeatsMain) {
        initComponents();
        this.btnShowAllMain = btnShowAllMain;
        this.btnDeleteMain = btnDeleteMain;
        this.btnResetMain = btnResetMain;
        this.spSearchMain = spSearchMain;
        this.spSeatsMain = spSeatsMain;
        ((JSpinner.DefaultEditor) spSeats.getEditor()).getTextField().setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarInfo = new javax.swing.JLabel();
        pnlCarCatInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spSeats = new javax.swing.JSpinner();
        txtSurcharge = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        msgSurcharge = new javax.swing.JLabel();
        msgDiscount = new javax.swing.JLabel();
        msgSeats = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarInfo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblCarInfo.setText("Car Category Info");
        getContentPane().add(lblCarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        pnlCarCatInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Seats:");
        pnlCarCatInfo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 27, -1, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("SurchargeHr:");
        pnlCarCatInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Discount:");
        pnlCarCatInfo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 30));

        spSeats.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        spSeats.setModel(new javax.swing.SpinnerNumberModel(2, 2, 100, 1));
        pnlCarCatInfo.add(spSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        txtSurcharge.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtSurcharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurchargeActionPerformed(evt);
            }
        });
        pnlCarCatInfo.add(txtSurcharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 180, -1));

        txtDiscount.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        pnlCarCatInfo.add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("VND");
        pnlCarCatInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 117, -1, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setText("%");
        pnlCarCatInfo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, 30));

        msgSurcharge.setForeground(new java.awt.Color(255, 51, 51));
        pnlCarCatInfo.add(msgSurcharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 20));

        msgDiscount.setForeground(new java.awt.Color(255, 51, 51));
        pnlCarCatInfo.add(msgDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 20));

        msgSeats.setForeground(new java.awt.Color(255, 51, 51));
        pnlCarCatInfo.add(msgSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 180, 20));

        getContentPane().add(pnlCarCatInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 490, 300));

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 100, 40));

        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 100, 40));

        setSize(new java.awt.Dimension(693, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSurchargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurchargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurchargeActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtDiscount.setText("");
        txtSurcharge.setText("");
        spSeats.setValue(2);
        msgDiscount.setText("");
        msgSeats.setText("");
        msgSurcharge.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        int seats = (Integer) spSeats.getValue();
        int surchargeHr = 0;
        float discount = 0;
        try {
            surchargeHr = Integer.parseInt(txtSurcharge.getText());
        } catch (NumberFormatException e) {
        }
        try {
            int temp = Integer.parseInt(txtDiscount.getText());
            discount = (float)Math.round(temp)/100;
        } catch (NumberFormatException e) {
        }
        CarCategoryDAO carCatDAO = new CarCategoryDAO();
        if (validate(seats, surchargeHr, discount)) {
            if (carCatDAO.insert(new CarCategoryDTO(seats, surchargeHr, discount))) {
                JOptionPane.showMessageDialog(null, "Insert success");
                btnDeleteMain.setEnabled(false);
                spSearchMain.setValue(2);
                btnShowAllMain.doClick();
                btnResetMain.doClick();
                spSeatsMain.setValue(2);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Insert failed");
            }

        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private boolean validate(int seats, int surchargeHr, float discount) {
        boolean check = true;
        CarCategoryDAO carCatDAO = new CarCategoryDAO();
        if (carCatDAO.findExisting(seats)) {
            msgSeats.setText("Number of seats existed.");
            check = false;
        } else {
            msgSeats.setText("");
        }
        if (surchargeHr < 1) {
            msgSurcharge.setText("Sucharge is number format.");
            check = false;
        } else {
            msgSurcharge.setText("");
        }
        if (discount > 0 && discount < 1) {
            msgDiscount.setText("");
        } else {
            msgDiscount.setText("Discount is invalid.");
            check = false;
        }
        return check;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarCatInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarCatInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarCatInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarCatInsertFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarCatInsertFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCarInfo;
    private javax.swing.JLabel msgDiscount;
    private javax.swing.JLabel msgSeats;
    private javax.swing.JLabel msgSurcharge;
    private javax.swing.JPanel pnlCarCatInfo;
    private javax.swing.JSpinner spSeats;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtSurcharge;
    // End of variables declaration//GEN-END:variables
}
